from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]

SOURCES = {
    "quality_plain": "Quality documents available upon request",
    "quality_short": "Quality documents available upon request · OEM/ODM",
    "quality_footer": "Yuchen Water · Quality documents available upon request · OEM/ODM ·",
    "quality_management": "Quality management documents available upon request.",
    "halal_about": "Halal-related documents are available upon request for qualified orders.",
    "rights": "All rights reserved.",
    "privacy": "Privacy Policy",
    "cert_footer": "selected NSF/ANSI and Halal-related documents available on request",
    "success_1": "Thank you. Your inquiry has been submitted successfully and sent to Yuchen Water at expresswater025@gmail.com.",
    "success_2": "Our sales engineer will contact you as soon as possible.",
    "success_3": "You can also contact us anytime on WhatsApp +86-19908311885 or email expresswater025@gmail.com.",
    "schema_quality_name": '"name":"Quality documents"',
    "schema_quality_value": "Selected products can be supplied or tested according to NSF/ANSI 42, 53 and 58 requirements. ISO 9001, CE, SGS and Halal-related documents are available upon request by product model and market requirement.",
    "cred_1": "Selected products can be supplied or tested according to NSF/ANSI 42, 53 and 58 requirements",
    "cred_2": "ISO 9001 quality management documents available upon request",
    "cred_3": "CE documents available upon request where applicable",
    "cred_4": "SGS test reports available upon request where applicable",
    "cred_5": "Halal-related documents available upon request where applicable",
    "cred_cat_1": "product testing support",
    "cred_cat_2": "quality document",
    "cred_cat_3": "market document",
    "cred_cat_4": "third-party test document",
    "schema_quality_value_short": "Selected products can be supplied or tested according to NSF/ANSI requirements. ISO 9001, CE, SGS and Halal-related documents are available upon request.",
    "cert_tail": "ISO 9001, CE, SGS and Halal-related documents are available upon request.",
    "cat_q1": "Can this category be supplied with private-label packaging?",
    "cat_a1": "Yes. Yuchen Water supports product labels, sealed bags, color boxes, instruction sheets, master cartons and pallet marks for OEM/ODM orders.",
    "cat_q2": "What information is needed for a quotation?",
    "cat_a2": "Please send product type, target size, specification, estimated quantity, destination port and any branding or compliance requirements.",
    "cat_q3": "Are certification documents available?",
    "org_description": "Yuchen Water is a China water filtration manufacturer supplying PP, CTO, GAC, T33, UF, RO membrane, water purifier, water dispenser and filter housing products for global B2B OEM and ODM buyers.",
    "org_slogan": "Industrial-Grade Water Purification & OEM Solutions",
    "website_description": "Global water filter and reverse osmosis system manufacturer for OEM/ODM wholesale buyers",
    "worldwide": "Worldwide",
    "award_1": "27+ years of water filtration manufacturing experience",
    "award_2": "50+ export markets",
    "award_3": "200+ water filtration product SKU range",
    "crumb_home": '"name":"Home"',
    "crumb_products": '"name":"Products"',
}

T = {
    "ar": {
        "quality_plain": "وثائق الجودة متاحة عند الطلب",
        "quality_short": "وثائق الجودة متاحة عند الطلب · OEM/ODM",
        "quality_footer": "Yuchen Water · وثائق الجودة متاحة عند الطلب · OEM/ODM ·",
        "quality_management": "وثائق إدارة الجودة متاحة عند الطلب.",
        "halal_about": "يمكن توفير الوثائق المتعلقة بالحلال عند الطلب للطلبات المؤهلة.",
        "rights": "جميع الحقوق محفوظة.",
        "privacy": "سياسة الخصوصية",
        "cert_footer": "وثائق NSF/ANSI المختارة والوثائق المتعلقة بالحلال متاحة عند الطلب",
        "success_1": "شكرًا لك. تم إرسال استفسارك بنجاح إلى Yuchen Water عبر expresswater025@gmail.com.",
        "success_2": "سيتواصل معك مهندس المبيعات لدينا في أقرب وقت ممكن.",
        "success_3": "يمكنك أيضًا التواصل معنا في أي وقت عبر WhatsApp +86-19908311885 أو البريد الإلكتروني expresswater025@gmail.com.",
        "schema_quality_name": '"name":"وثائق الجودة"',
        "schema_quality_value": "يمكن توريد أو اختبار منتجات مختارة وفق متطلبات NSF/ANSI 42 و53 و58. تتوفر وثائق ISO 9001 وCE وSGS والوثائق المتعلقة بالحلال عند الطلب حسب طراز المنتج ومتطلبات السوق.",
        "schema_quality_value_short": "يمكن توريد أو اختبار منتجات مختارة وفق متطلبات NSF/ANSI. تتوفر وثائق ISO 9001 وCE وSGS والوثائق المتعلقة بالحلال عند الطلب.",
        "cert_tail": "تتوفر وثائق ISO 9001 وCE وSGS والوثائق المتعلقة بالحلال عند الطلب.",
        "cat_q1": "هل يمكن توريد هذه الفئة بتغليف بعلامة خاصة؟",
        "cat_a1": "نعم. تدعم Yuchen Water ملصقات المنتجات والأكياس المحكمة والصناديق الملونة وأوراق التعليمات والكرتون الرئيسي وعلامات المنصات لطلبات OEM/ODM.",
        "cat_q2": "ما المعلومات المطلوبة للحصول على عرض سعر؟",
        "cat_a2": "يرجى إرسال نوع المنتج والحجم المطلوب والمواصفات والكمية المقدرة وميناء الوصول وأي متطلبات للعلامة التجارية أو الامتثال.",
        "cat_q3": "هل تتوفر وثائق الشهادات؟",
        "org_description": "Yuchen Water شركة صينية مصنعة لمنتجات ترشيح المياه، وتورّد منتجات PP وCTO وGAC وT33 وUF وأغشية RO وأجهزة تنقية المياه والمبردات وحاويات الفلاتر لمشتري B2B بنظام OEM/ODM حول العالم.",
        "org_slogan": "حلول معالجة مياه صناعية وتصنيع OEM",
        "website_description": "مصنع عالمي لفلاتر المياه وأنظمة التناضح العكسي لمشتري الجملة OEM/ODM",
        "worldwide": "حول العالم",
        "award_1": "أكثر من 27 عامًا من خبرة تصنيع منتجات ترشيح المياه",
        "award_2": "أكثر من 50 سوقًا للتصدير",
        "award_3": "أكثر من 200 رمز SKU لمنتجات ترشيح المياه",
        "crumb_home": '"name":"الرئيسية"',
        "crumb_products": '"name":"المنتجات"',
    },
    "fa": {
        "quality_plain": "اسناد کیفیت بنا به درخواست ارائه می‌شود",
        "quality_short": "اسناد کیفیت بنا به درخواست ارائه می‌شود · OEM/ODM",
        "quality_footer": "Yuchen Water · اسناد کیفیت بنا به درخواست ارائه می‌شود · OEM/ODM ·",
        "quality_management": "اسناد مدیریت کیفیت بنا به درخواست ارائه می‌شود.",
        "halal_about": "اسناد مرتبط با حلال برای سفارش‌های واجد شرایط بنا به درخواست ارائه می‌شود.",
        "rights": "تمام حقوق محفوظ است.",
        "privacy": "سیاست حفظ حریم خصوصی",
        "cert_footer": "اسناد منتخب NSF/ANSI و اسناد مرتبط با حلال بنا به درخواست ارائه می‌شود",
        "success_1": "سپاسگزاریم. درخواست شما با موفقیت به Yuchen Water در expresswater025@gmail.com ارسال شد.",
        "success_2": "مهندس فروش ما در سریع‌ترین زمان ممکن با شما تماس خواهد گرفت.",
        "success_3": "همچنین می‌توانید هر زمان از طریق WhatsApp +86-19908311885 یا ایمیل expresswater025@gmail.com با ما تماس بگیرید.",
        "schema_quality_name": '"name":"اسناد کیفیت"',
        "schema_quality_value": "محصولات منتخب می‌توانند مطابق الزامات NSF/ANSI 42، 53 و 58 تأمین یا آزمایش شوند. اسناد ISO 9001، CE، SGS و اسناد مرتبط با حلال بنا بر مدل محصول و نیاز بازار قابل ارائه است.",
        "schema_quality_value_short": "محصولات منتخب می‌توانند مطابق الزامات NSF/ANSI تأمین یا آزمایش شوند. اسناد ISO 9001، CE، SGS و اسناد مرتبط با حلال بنا به درخواست ارائه می‌شود.",
        "cert_tail": "اسناد ISO 9001، CE، SGS و اسناد مرتبط با حلال بنا به درخواست ارائه می‌شود.",
        "cat_q1": "آیا این دسته با بسته‌بندی برند خصوصی قابل عرضه است؟",
        "cat_a1": "بله. Yuchen Water برای سفارش‌های OEM/ODM از برچسب محصول، کیسه مهروموم‌شده، جعبه رنگی، برگه راهنما، کارتن مادر و علائم پالت پشتیبانی می‌کند.",
        "cat_q2": "برای دریافت قیمت چه اطلاعاتی لازم است؟",
        "cat_a2": "لطفاً نوع محصول، اندازه موردنظر، مشخصات، تعداد تقریبی، بندر مقصد و الزامات برندینگ یا انطباق را ارسال کنید.",
        "cat_q3": "آیا اسناد گواهی قابل ارائه است؟",
        "org_description": "Yuchen Water تولیدکننده چینی محصولات فیلتراسیون آب است و PP، CTO، GAC، T33، UF، ممبران RO، دستگاه تصفیه آب، آبسردکن و هوزینگ فیلتر را برای خریداران B2B OEM/ODM جهانی تأمین می‌کند.",
        "org_slogan": "تصفیه آب صنعتی و راهکارهای OEM",
        "website_description": "تولیدکننده جهانی فیلتر آب و سیستم اسمز معکوس برای خریداران عمده OEM/ODM",
        "worldwide": "در سراسر جهان",
        "award_1": "بیش از 27 سال تجربه تولید محصولات فیلتراسیون آب",
        "award_2": "بیش از 50 بازار صادراتی",
        "award_3": "بیش از 200 SKU محصول فیلتراسیون آب",
        "crumb_home": '"name":"خانه"',
        "crumb_products": '"name":"محصولات"',
    },
    "he": {
        "quality_plain": "מסמכי איכות זמינים לפי בקשה",
        "quality_short": "מסמכי איכות זמינים לפי בקשה · OEM/ODM",
        "quality_footer": "Yuchen Water · מסמכי איכות זמינים לפי בקשה · OEM/ODM ·",
        "quality_management": "מסמכי ניהול איכות זמינים לפי בקשה.",
        "halal_about": "מסמכים הקשורים ל-Halal זמינים לפי בקשה עבור הזמנות מתאימות.",
        "rights": "כל הזכויות שמורות.",
        "privacy": "מדיניות פרטיות",
        "cert_footer": "מסמכי NSF/ANSI נבחרים ומסמכים הקשורים ל-Halal זמינים לפי בקשה",
        "success_1": "תודה. הפנייה שלך נשלחה בהצלחה אל Yuchen Water בכתובת expresswater025@gmail.com.",
        "success_2": "מהנדס המכירות שלנו יצור איתך קשר בהקדם האפשרי.",
        "success_3": "ניתן לפנות אלינו בכל עת גם ב-WhatsApp +86-19908311885 או בדוא\"ל expresswater025@gmail.com.",
        "schema_quality_name": '"name":"מסמכי איכות"',
        "schema_quality_value": "מוצרים נבחרים יכולים להיות מסופקים או להיבדק לפי דרישות NSF/ANSI 42, 53 ו-58. מסמכי ISO 9001, CE, SGS ומסמכים הקשורים ל-Halal זמינים לפי בקשה לפי דגם המוצר ודרישות השוק.",
        "schema_quality_value_short": "מוצרים נבחרים יכולים להיות מסופקים או להיבדק לפי דרישות NSF/ANSI. מסמכי ISO 9001, CE, SGS ומסמכים הקשורים ל-Halal זמינים לפי בקשה.",
        "cert_tail": "מסמכי ISO 9001, CE, SGS ומסמכים הקשורים ל-Halal זמינים לפי בקשה.",
        "cat_q1": "האם ניתן לספק קטגוריה זו באריזת מותג פרטי?",
        "cat_a1": "כן. Yuchen Water תומכת בתוויות מוצר, שקיות אטומות, קופסאות צבע, דפי הוראות, קרטוני מאסטר וסימוני משטח להזמנות OEM/ODM.",
        "cat_q2": "איזה מידע נדרש להצעת מחיר?",
        "cat_a2": "נא לשלוח סוג מוצר, גודל יעד, מפרט, כמות משוערת, נמל יעד וכל דרישת מיתוג או תאימות.",
        "cat_q3": "האם מסמכי הסמכה זמינים?",
        "org_description": "Yuchen Water היא יצרנית סינית של מוצרי סינון מים המספקת PP, CTO, GAC, T33, UF, ממברנות RO, מטהרי מים, מתקני מים ובתי מסנן לקנייני B2B OEM/ODM ברחבי העולם.",
        "org_slogan": "טיפול מים תעשייתי ופתרונות OEM",
        "website_description": "יצרן גלובלי של מסנני מים ומערכות אוסמוזה הפוכה לקנייני OEM/ODM סיטונאיים",
        "worldwide": "ברחבי העולם",
        "award_1": "יותר מ-27 שנות ניסיון בייצור מוצרי סינון מים",
        "award_2": "יותר מ-50 שווקי יצוא",
        "award_3": "יותר מ-200 SKU של מוצרי סינון מים",
        "crumb_home": '"name":"בית"',
        "crumb_products": '"name":"מוצרים"',
    },
    "id": {
        "quality_plain": "Dokumen kualitas tersedia atas permintaan",
        "quality_short": "Dokumen kualitas tersedia atas permintaan · OEM/ODM",
        "quality_footer": "Yuchen Water · dokumen kualitas tersedia atas permintaan · OEM/ODM ·",
        "quality_management": "Dokumen manajemen kualitas tersedia atas permintaan.",
        "halal_about": "Dokumen terkait Halal tersedia atas permintaan untuk pesanan yang memenuhi syarat.",
        "rights": "Hak cipta dilindungi.",
        "privacy": "Kebijakan Privasi",
        "cert_footer": "dokumen NSF/ANSI terpilih dan dokumen terkait Halal tersedia atas permintaan",
        "success_1": "Terima kasih. Permintaan Anda berhasil dikirim ke Yuchen Water di expresswater025@gmail.com.",
        "success_2": "Insinyur penjualan kami akan menghubungi Anda secepat mungkin.",
        "success_3": "Anda juga dapat menghubungi kami kapan saja melalui WhatsApp +86-19908311885 atau email expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Dokumen kualitas"',
        "schema_quality_value": "Produk tertentu dapat dipasok atau diuji sesuai persyaratan NSF/ANSI 42, 53 dan 58. Dokumen ISO 9001, CE, SGS dan terkait Halal tersedia atas permintaan sesuai model produk dan kebutuhan pasar.",
        "schema_quality_value_short": "Produk tertentu dapat dipasok atau diuji sesuai persyaratan NSF/ANSI. Dokumen ISO 9001, CE, SGS dan terkait Halal tersedia atas permintaan.",
        "cert_tail": "Dokumen ISO 9001, CE, SGS dan terkait Halal tersedia atas permintaan.",
        "cat_q1": "Apakah kategori ini dapat dipasok dengan kemasan private label?",
        "cat_a1": "Ya. Yuchen Water mendukung label produk, kantong segel, kotak warna, lembar instruksi, karton master dan tanda palet untuk pesanan OEM/ODM.",
        "cat_q2": "Informasi apa yang diperlukan untuk penawaran harga?",
        "cat_a2": "Silakan kirim jenis produk, ukuran target, spesifikasi, perkiraan jumlah, pelabuhan tujuan dan kebutuhan branding atau kepatuhan.",
        "cat_q3": "Apakah dokumen sertifikasi tersedia?",
        "org_description": "Yuchen Water adalah produsen produk filtrasi air dari Tiongkok yang memasok PP, CTO, GAC, T33, UF, membran RO, pemurni air, dispenser air dan housing filter untuk pembeli B2B OEM/ODM global.",
        "org_slogan": "Pengolahan air industri dan solusi OEM",
        "website_description": "Produsen global filter air dan sistem reverse osmosis untuk pembeli grosir OEM/ODM",
        "worldwide": "Seluruh dunia",
        "award_1": "Lebih dari 27 tahun pengalaman manufaktur filtrasi air",
        "award_2": "Lebih dari 50 pasar ekspor",
        "award_3": "Lebih dari 200 SKU produk filtrasi air",
        "crumb_home": '"name":"Beranda"',
        "crumb_products": '"name":"Produk"',
    },
    "th": {
        "quality_plain": "เอกสารคุณภาพมีให้ตามคำขอ",
        "quality_short": "เอกสารคุณภาพมีให้ตามคำขอ · OEM/ODM",
        "quality_footer": "Yuchen Water · เอกสารคุณภาพมีให้ตามคำขอ · OEM/ODM ·",
        "quality_management": "เอกสารการจัดการคุณภาพมีให้ตามคำขอ.",
        "halal_about": "เอกสารที่เกี่ยวข้องกับ Halal มีให้ตามคำขอสำหรับคำสั่งซื้อที่เข้าเงื่อนไข.",
        "rights": "สงวนลิขสิทธิ์.",
        "privacy": "นโยบายความเป็นส่วนตัว",
        "cert_footer": "เอกสาร NSF/ANSI ที่เกี่ยวข้องและเอกสาร Halal มีให้ตามคำขอ",
        "success_1": "ขอบคุณ คำขอของคุณถูกส่งถึง Yuchen Water ที่ expresswater025@gmail.com สำเร็จแล้ว.",
        "success_2": "วิศวกรฝ่ายขายของเราจะติดต่อคุณโดยเร็วที่สุด.",
        "success_3": "คุณสามารถติดต่อเราได้ตลอดเวลาทาง WhatsApp +86-19908311885 หรืออีเมล expresswater025@gmail.com.",
        "schema_quality_name": '"name":"เอกสารคุณภาพ"',
        "schema_quality_value": "ผลิตภัณฑ์บางรุ่นสามารถจัดส่งหรือทดสอบตามข้อกำหนด NSF/ANSI 42, 53 และ 58 ได้ เอกสาร ISO 9001, CE, SGS และ Halal มีให้ตามคำขอโดยขึ้นอยู่กับรุ่นสินค้าและข้อกำหนดตลาด.",
        "schema_quality_value_short": "ผลิตภัณฑ์บางรุ่นสามารถจัดส่งหรือทดสอบตามข้อกำหนด NSF/ANSI ได้ เอกสาร ISO 9001, CE, SGS และ Halal มีให้ตามคำขอ.",
        "cert_tail": "เอกสาร ISO 9001, CE, SGS และ Halal มีให้ตามคำขอ.",
        "cat_q1": "หมวดหมู่นี้สามารถจัดส่งพร้อมบรรจุภัณฑ์แบรนด์ส่วนตัวได้หรือไม่?",
        "cat_a1": "ได้ Yuchen Water รองรับฉลากสินค้า ถุงซีล กล่องสี ใบคำแนะนำ กล่องหลัก และเครื่องหมายพาเลทสำหรับคำสั่งซื้อ OEM/ODM.",
        "cat_q2": "ต้องใช้ข้อมูลใดสำหรับใบเสนอราคา?",
        "cat_a2": "กรุณาส่งประเภทสินค้า ขนาดเป้าหมาย สเปก จำนวนโดยประมาณ ท่าเรือปลายทาง และข้อกำหนดด้านแบรนด์หรือการปฏิบัติตามมาตรฐาน.",
        "cat_q3": "มีเอกสารรับรองหรือไม่?",
        "org_description": "Yuchen Water เป็นผู้ผลิตผลิตภัณฑ์กรองน้ำจากจีน จัดหา PP, CTO, GAC, T33, UF, เมมเบรน RO, เครื่องกรองน้ำ, ตู้กดน้ำ และเฮาส์ซิ่งกรองให้ผู้ซื้อ B2B OEM/ODM ทั่วโลก.",
        "org_slogan": "การบำบัดน้ำอุตสาหกรรมและโซลูชัน OEM",
        "website_description": "ผู้ผลิตตัวกรองน้ำและระบบ RO ระดับโลกสำหรับผู้ซื้อขายส่ง OEM/ODM",
        "worldwide": "ทั่วโลก",
        "award_1": "ประสบการณ์ผลิตระบบกรองน้ำมากกว่า 27 ปี",
        "award_2": "ตลาดส่งออกมากกว่า 50 ประเทศ",
        "award_3": "SKU ผลิตภัณฑ์กรองน้ำมากกว่า 200 รายการ",
        "crumb_home": '"name":"หน้าแรก"',
        "crumb_products": '"name":"ผลิตภัณฑ์"',
    },
    "ms": {
        "quality_plain": "Dokumen kualiti tersedia atas permintaan",
        "quality_short": "Dokumen kualiti tersedia atas permintaan · OEM/ODM",
        "quality_footer": "Yuchen Water · dokumen kualiti tersedia atas permintaan · OEM/ODM ·",
        "quality_management": "Dokumen pengurusan kualiti tersedia atas permintaan.",
        "halal_about": "Dokumen berkaitan Halal tersedia atas permintaan untuk pesanan yang layak.",
        "rights": "Hak cipta terpelihara.",
        "privacy": "Dasar Privasi",
        "cert_footer": "dokumen NSF/ANSI terpilih dan dokumen berkaitan Halal tersedia atas permintaan",
        "success_1": "Terima kasih. Pertanyaan anda berjaya dihantar kepada Yuchen Water di expresswater025@gmail.com.",
        "success_2": "Jurutera jualan kami akan menghubungi anda secepat mungkin.",
        "success_3": "Anda juga boleh menghubungi kami pada bila-bila masa melalui WhatsApp +86-19908311885 atau e-mel expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Dokumen kualiti"',
        "schema_quality_value": "Produk terpilih boleh dibekalkan atau diuji mengikut keperluan NSF/ANSI 42, 53 dan 58. Dokumen ISO 9001, CE, SGS dan berkaitan Halal tersedia atas permintaan mengikut model produk dan keperluan pasaran.",
        "schema_quality_value_short": "Produk terpilih boleh dibekalkan atau diuji mengikut keperluan NSF/ANSI. Dokumen ISO 9001, CE, SGS dan berkaitan Halal tersedia atas permintaan.",
        "cert_tail": "Dokumen ISO 9001, CE, SGS dan berkaitan Halal tersedia atas permintaan.",
        "cat_q1": "Bolehkah kategori ini dibekalkan dengan pembungkusan label peribadi?",
        "cat_a1": "Ya. Yuchen Water menyokong label produk, beg bersegel, kotak warna, helaian arahan, karton induk dan tanda palet untuk pesanan OEM/ODM.",
        "cat_q2": "Maklumat apa yang diperlukan untuk sebut harga?",
        "cat_a2": "Sila hantar jenis produk, saiz sasaran, spesifikasi, anggaran kuantiti, pelabuhan destinasi dan keperluan penjenamaan atau pematuhan.",
        "cat_q3": "Adakah dokumen pensijilan tersedia?",
        "org_description": "Yuchen Water ialah pengeluar produk penapisan air dari China yang membekalkan PP, CTO, GAC, T33, UF, membran RO, penulen air, dispenser air dan perumah penapis untuk pembeli B2B OEM/ODM global.",
        "org_slogan": "Rawatan air industri dan penyelesaian OEM",
        "website_description": "Pengeluar global penapis air dan sistem osmosis songsang untuk pembeli borong OEM/ODM",
        "worldwide": "Seluruh dunia",
        "award_1": "Lebih 27 tahun pengalaman pembuatan penapisan air",
        "award_2": "Lebih 50 pasaran eksport",
        "award_3": "Lebih 200 SKU produk penapisan air",
        "crumb_home": '"name":"Laman utama"',
        "crumb_products": '"name":"Produk"',
    },
    "tl": {
        "quality_plain": "Available ang mga dokumento ng kalidad kapag hiniling",
        "quality_short": "Available ang mga dokumento ng kalidad kapag hiniling · OEM/ODM",
        "quality_footer": "Yuchen Water · available ang mga dokumento ng kalidad kapag hiniling · OEM/ODM ·",
        "quality_management": "Available ang mga dokumento sa pamamahala ng kalidad kapag hiniling.",
        "halal_about": "Available ang mga dokumentong may kaugnayan sa Halal kapag hiniling para sa kwalipikadong mga order.",
        "rights": "Lahat ng karapatan ay nakalaan.",
        "privacy": "Patakaran sa Privacy",
        "cert_footer": "available kapag hiniling ang piling NSF/ANSI at mga dokumentong may kaugnayan sa Halal",
        "success_1": "Salamat. Matagumpay na naipadala ang iyong inquiry sa Yuchen Water sa expresswater025@gmail.com.",
        "success_2": "Makikipag-ugnayan sa iyo ang aming sales engineer sa lalong madaling panahon.",
        "success_3": "Maaari mo rin kaming kontakin anumang oras sa WhatsApp +86-19908311885 o email expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Mga dokumento ng kalidad"',
        "schema_quality_value": "Maaaring ibigay o subukan ang piling produkto ayon sa mga kinakailangan ng NSF/ANSI 42, 53 at 58. Available kapag hiniling ang mga dokumento ng ISO 9001, CE, SGS at Halal ayon sa modelo ng produkto at pangangailangan ng merkado.",
        "schema_quality_value_short": "Maaaring ibigay o subukan ang piling produkto ayon sa mga kinakailangan ng NSF/ANSI. Available kapag hiniling ang mga dokumento ng ISO 9001, CE, SGS at Halal.",
        "cert_tail": "Available kapag hiniling ang mga dokumento ng ISO 9001, CE, SGS at Halal.",
        "cat_q1": "Maaari bang ibigay ang kategoryang ito na may private-label packaging?",
        "cat_a1": "Oo. Sinusuportahan ng Yuchen Water ang product labels, sealed bags, color boxes, instruction sheets, master cartons at pallet marks para sa OEM/ODM orders.",
        "cat_q2": "Anong impormasyon ang kailangan para sa quotation?",
        "cat_a2": "Ipadala ang uri ng produkto, target na laki, specification, tinatayang dami, destination port at anumang branding o compliance requirements.",
        "cat_q3": "Available ba ang certification documents?",
        "org_description": "Ang Yuchen Water ay manufacturer ng water filtration products mula China na nagsusuplay ng PP, CTO, GAC, T33, UF, RO membrane, water purifier, water dispenser at filter housing para sa global B2B OEM/ODM buyers.",
        "org_slogan": "Industrial water treatment at OEM solutions",
        "website_description": "Global manufacturer ng water filters at reverse osmosis systems para sa OEM/ODM wholesale buyers",
        "worldwide": "Buong mundo",
        "award_1": "Mahigit 27 taon ng karanasan sa paggawa ng water filtration products",
        "award_2": "Mahigit 50 export markets",
        "award_3": "Mahigit 200 SKU ng water filtration products",
        "crumb_home": '"name":"Pangunahing pahina"',
        "crumb_products": '"name":"Mga Produkto"',
    },
    "bn": {
        "quality_plain": "গুণমান সংক্রান্ত নথি অনুরোধে পাওয়া যাবে",
        "quality_short": "গুণমান সংক্রান্ত নথি অনুরোধে পাওয়া যাবে · OEM/ODM",
        "quality_footer": "Yuchen Water · গুণমান সংক্রান্ত নথি অনুরোধে পাওয়া যাবে · OEM/ODM ·",
        "quality_management": "গুণমান ব্যবস্থাপনা নথি অনুরোধে পাওয়া যাবে।",
        "halal_about": "যোগ্য অর্ডারের জন্য Halal-সম্পর্কিত নথি অনুরোধে পাওয়া যাবে।",
        "rights": "সর্বস্বত্ব সংরক্ষিত।",
        "privacy": "গোপনীয়তা নীতি",
        "cert_footer": "নির্বাচিত NSF/ANSI ও Halal-সম্পর্কিত নথি অনুরোধে পাওয়া যাবে",
        "success_1": "ধন্যবাদ। আপনার অনুসন্ধান সফলভাবে Yuchen Water-এ expresswater025@gmail.com ঠিকানায় পাঠানো হয়েছে।",
        "success_2": "আমাদের বিক্রয় প্রকৌশলী যত দ্রুত সম্ভব আপনার সঙ্গে যোগাযোগ করবেন।",
        "success_3": "আপনি যেকোনো সময় WhatsApp +86-19908311885 অথবা ইমেইল expresswater025@gmail.com-এ আমাদের সঙ্গে যোগাযোগ করতে পারেন।",
        "schema_quality_name": '"name":"গুণমান সংক্রান্ত নথি"',
        "schema_quality_value": "নির্বাচিত পণ্য NSF/ANSI 42, 53 ও 58 প্রয়োজনীয়তা অনুযায়ী সরবরাহ বা পরীক্ষা করা যেতে পারে। পণ্যের মডেল ও বাজারের প্রয়োজন অনুযায়ী ISO 9001, CE, SGS এবং Halal-সম্পর্কিত নথি অনুরোধে পাওয়া যাবে।",
        "schema_quality_value_short": "নির্বাচিত পণ্য NSF/ANSI প্রয়োজনীয়তা অনুযায়ী সরবরাহ বা পরীক্ষা করা যেতে পারে। ISO 9001, CE, SGS এবং Halal-সম্পর্কিত নথি অনুরোধে পাওয়া যাবে।",
        "cert_tail": "ISO 9001, CE, SGS এবং Halal-সম্পর্কিত নথি অনুরোধে পাওয়া যাবে।",
        "cat_q1": "এই ক্যাটাগরি কি প্রাইভেট-লেবেল প্যাকেজিংসহ সরবরাহ করা যায়?",
        "cat_a1": "হ্যাঁ। Yuchen Water OEM/ODM অর্ডারের জন্য পণ্য লেবেল, সিল করা ব্যাগ, কালার বক্স, নির্দেশিকা শীট, মাস্টার কার্টন এবং প্যালেট মার্ক সমর্থন করে।",
        "cat_q2": "কোটেশনের জন্য কী তথ্য প্রয়োজন?",
        "cat_a2": "অনুগ্রহ করে পণ্যের ধরন, লক্ষ্য আকার, স্পেসিফিকেশন, আনুমানিক পরিমাণ, গন্তব্য বন্দর এবং ব্র্যান্ডিং বা কমপ্লায়েন্স প্রয়োজনীয়তা পাঠান।",
        "cat_q3": "সার্টিফিকেশন নথি কি পাওয়া যায়?",
        "org_description": "Yuchen Water চীনের একটি পানি ফিল্ট্রেশন পণ্য প্রস্তুতকারক, যা বৈশ্বিক B2B OEM/ODM ক্রেতাদের জন্য PP, CTO, GAC, T33, UF, RO মেমব্রেন, পানি বিশুদ্ধকারী, পানি ডিসপেনসার ও ফিল্টার হাউজিং সরবরাহ করে।",
        "org_slogan": "শিল্প পানি পরিশোধন ও OEM সমাধান",
        "website_description": "OEM/ODM পাইকারি ক্রেতাদের জন্য বৈশ্বিক পানি ফিল্টার ও রিভার্স অসমোসিস সিস্টেম প্রস্তুতকারক",
        "worldwide": "বিশ্বব্যাপী",
        "award_1": "পানি ফিল্ট্রেশন উৎপাদনে ২৭ বছরের বেশি অভিজ্ঞতা",
        "award_2": "৫০টির বেশি রপ্তানি বাজার",
        "award_3": "২০০টির বেশি পানি ফিল্ট্রেশন পণ্য SKU",
        "crumb_home": '"name":"হোম"',
        "crumb_products": '"name":"পণ্য"',
    },
    "sw": {
        "quality_plain": "Nyaraka za ubora zinapatikana kwa ombi",
        "quality_short": "Nyaraka za ubora zinapatikana kwa ombi · OEM/ODM",
        "quality_footer": "Yuchen Water · nyaraka za ubora zinapatikana kwa ombi · OEM/ODM ·",
        "quality_management": "Nyaraka za usimamizi wa ubora zinapatikana kwa ombi.",
        "halal_about": "Nyaraka zinazohusiana na Halal zinapatikana kwa ombi kwa oda zinazostahili.",
        "rights": "Haki zote zimehifadhiwa.",
        "privacy": "Sera ya Faragha",
        "cert_footer": "nyaraka teule za NSF/ANSI na zinazohusiana na Halal zinapatikana kwa ombi",
        "success_1": "Asante. Ombi lako limetumwa kwa mafanikio kwa Yuchen Water kupitia expresswater025@gmail.com.",
        "success_2": "Mhandisi wetu wa mauzo atawasiliana nawe haraka iwezekanavyo.",
        "success_3": "Unaweza pia kuwasiliana nasi wakati wowote kupitia WhatsApp +86-19908311885 au barua pepe expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Nyaraka za ubora"',
        "schema_quality_value": "Bidhaa teule zinaweza kutolewa au kupimwa kulingana na mahitaji ya NSF/ANSI 42, 53 na 58. Nyaraka za ISO 9001, CE, SGS na zinazohusiana na Halal zinapatikana kwa ombi kulingana na modeli ya bidhaa na mahitaji ya soko.",
        "schema_quality_value_short": "Bidhaa teule zinaweza kutolewa au kupimwa kulingana na mahitaji ya NSF/ANSI. Nyaraka za ISO 9001, CE, SGS na zinazohusiana na Halal zinapatikana kwa ombi.",
        "cert_tail": "Nyaraka za ISO 9001, CE, SGS na zinazohusiana na Halal zinapatikana kwa ombi.",
        "cat_q1": "Je, kundi hili linaweza kutolewa na kifungashio cha chapa binafsi?",
        "cat_a1": "Ndiyo. Yuchen Water hutoa lebo za bidhaa, mifuko iliyofungwa, boksi za rangi, karatasi za maelekezo, katoni kuu na alama za paleti kwa oda za OEM/ODM.",
        "cat_q2": "Ni taarifa gani zinahitajika kwa nukuu ya bei?",
        "cat_a2": "Tafadhali tuma aina ya bidhaa, ukubwa unaolengwa, vipimo, kiasi kinachokadiriwa, bandari ya mwisho na mahitaji yoyote ya chapa au ufuataji.",
        "cat_q3": "Je, nyaraka za vyeti zinapatikana?",
        "org_description": "Yuchen Water ni mtengenezaji wa bidhaa za uchujaji maji kutoka China, akisambaza PP, CTO, GAC, T33, UF, membrane za RO, visafishaji maji, dispensa za maji na nyumba za vichujio kwa wanunuzi wa B2B OEM/ODM duniani.",
        "org_slogan": "Usafishaji maji wa viwandani na suluhisho za OEM",
        "website_description": "Mtengenezaji wa kimataifa wa vichujio vya maji na mifumo ya reverse osmosis kwa wanunuzi wa jumla OEM/ODM",
        "worldwide": "Duniani kote",
        "award_1": "Zaidi ya miaka 27 ya uzoefu wa utengenezaji wa uchujaji maji",
        "award_2": "Zaidi ya masoko 50 ya usafirishaji nje",
        "award_3": "Zaidi ya SKU 200 za bidhaa za uchujaji maji",
        "crumb_home": '"name":"Nyumbani"',
        "crumb_products": '"name":"Bidhaa"',
    },
    "af": {
        "quality_plain": "Kwaliteitsdokumente is op versoek beskikbaar",
        "quality_short": "Kwaliteitsdokumente is op versoek beskikbaar · OEM/ODM",
        "quality_footer": "Yuchen Water · kwaliteitsdokumente is op versoek beskikbaar · OEM/ODM ·",
        "quality_management": "Kwaliteitsbestuursdokumente is op versoek beskikbaar.",
        "halal_about": "Halal-verwante dokumente is op versoek beskikbaar vir kwalifiserende bestellings.",
        "rights": "Alle regte voorbehou.",
        "privacy": "Privaatheidsbeleid",
        "cert_footer": "geselekteerde NSF/ANSI- en Halal-verwante dokumente is op versoek beskikbaar",
        "success_1": "Dankie. Jou navraag is suksesvol aan Yuchen Water gestuur by expresswater025@gmail.com.",
        "success_2": "Ons verkoopsingenieur sal jou so gou as moontlik kontak.",
        "success_3": "Jy kan ons ook enige tyd kontak via WhatsApp +86-19908311885 of e-pos expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Kwaliteitsdokumente"',
        "schema_quality_value": "Geselekteerde produkte kan volgens NSF/ANSI 42, 53 en 58 vereistes verskaf of getoets word. ISO 9001-, CE-, SGS- en Halal-verwante dokumente is op versoek beskikbaar volgens produkmodel en markvereiste.",
        "schema_quality_value_short": "Geselekteerde produkte kan volgens NSF/ANSI-vereistes verskaf of getoets word. ISO 9001-, CE-, SGS- en Halal-verwante dokumente is op versoek beskikbaar.",
        "cert_tail": "ISO 9001-, CE-, SGS- en Halal-verwante dokumente is op versoek beskikbaar.",
        "cat_q1": "Kan hierdie kategorie met privaat-etiket verpakking voorsien word?",
        "cat_a1": "Ja. Yuchen Water ondersteun produketikette, verseëlde sakke, kleurhouers, instruksievelle, hoofkartonne en paletmerke vir OEM/ODM-bestellings.",
        "cat_q2": "Watter inligting is nodig vir 'n kwotasie?",
        "cat_a2": "Stuur asseblief produksoort, teikengrootte, spesifikasie, geskatte hoeveelheid, bestemmingshawe en enige handelsmerk- of voldoeningsvereistes.",
        "cat_q3": "Is sertifiseringsdokumente beskikbaar?",
        "org_description": "Yuchen Water is 'n Chinese vervaardiger van waterfiltrasieprodukte wat PP, CTO, GAC, T33, UF, RO-membrane, watersuiweraars, waterdispensers en filterbehuisings aan globale B2B OEM/ODM-kopers verskaf.",
        "org_slogan": "Industriële waterbehandeling en OEM-oplossings",
        "website_description": "Globale vervaardiger van waterfilters en omgekeerde-osmosestelsels vir OEM/ODM-groothandelkopers",
        "worldwide": "Wêreldwyd",
        "award_1": "Meer as 27 jaar ondervinding in waterfiltrasievervaardiging",
        "award_2": "Meer as 50 uitvoermarkte",
        "award_3": "Meer as 200 SKU's vir waterfiltrasieprodukte",
        "crumb_home": '"name":"Tuis"',
        "crumb_products": '"name":"Produkte"',
    },
}


def normalize_title(html: str) -> str:
    def replace_title(match: re.Match[str]) -> str:
        title = match.group(1)
        parts = [part.strip() for part in title.split("|")]
        if len(parts) >= 3 and parts[-1] == "Yuchen Water":
            middle = " ".join(parts[1:-1])
            if re.search(
                r"\b(product|inline filter|t33 inline filter|water purifier|filter cartridge|ro membrane|water dispenser|filter housing|carbon block|alkaline purifier|post t33|antibacterial mineralization)\b",
                middle,
                re.I,
            ):
                return f"<title>{parts[0]} | Yuchen Water</title>"
        return match.group(0)

    return re.sub(r"<title>(.*?)</title>", replace_title, html, flags=re.I | re.S)


def main() -> None:
    changed = 0
    for lang, translations in T.items():
        replacements = {source: translations[key] for key, source in SOURCES.items() if key in translations}
        first_quality_sentence = translations["schema_quality_value"].split(".", 1)[0]
        replacements[SOURCES["cred_1"]] = first_quality_sentence
        replacements[SOURCES["cred_2"]] = translations["quality_management"].rstrip(".")
        replacements[SOURCES["cred_3"]] = translations["cert_tail"].rstrip(".")
        replacements[SOURCES["cred_4"]] = translations["cert_tail"].rstrip(".")
        replacements[SOURCES["cred_5"]] = translations["cert_tail"].rstrip(".")
        replacements[SOURCES["cred_cat_1"]] = translations["quality_plain"]
        replacements[SOURCES["cred_cat_2"]] = translations["quality_plain"]
        replacements[SOURCES["cred_cat_3"]] = translations["quality_plain"]
        replacements[SOURCES["cred_cat_4"]] = translations["quality_plain"]
        for path in (ROOT / lang).glob("*.html"):
            original = path.read_text(encoding="utf-8")
            updated = original
            for source, target in replacements.items():
                updated = updated.replace(source, target)
            updated = normalize_title(updated)
            if updated != original:
                path.write_text(updated, encoding="utf-8")
                changed += 1
                print(path.relative_to(ROOT))
    print(f"changed_files={changed}")


if __name__ == "__main__":
    main()
