#!/usr/bin/env python3
"""Clean remaining UI and image-alt English snippets in priority languages."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
LANGS = ["ru", "es", "de", "fr", "vi", "ja", "uz", "kk", "ky"]

SELECT_LABEL = {
    "ru": "Выбрать язык",
    "es": "Seleccionar idioma",
    "de": "Sprache auswählen",
    "fr": "Choisir la langue",
    "vi": "Chọn ngôn ngữ",
    "ja": "言語を選択",
    "uz": "Tilni tanlash",
    "kk": "Тілді таңдау",
    "ky": "Тилди тандоо",
}

LOGO_ALT = {
    "ru": "Логотип Yuchen Sanyi",
    "es": "Logotipo de Yuchen Sanyi",
    "de": "Yuchen Sanyi Logo",
    "fr": "Logo Yuchen Sanyi",
    "vi": "Logo Yuchen Sanyi",
    "ja": "Yuchen Sanyiロゴ",
    "uz": "Yuchen Sanyi logotipi",
    "kk": "Yuchen Sanyi логотипі",
    "ky": "Yuchen Sanyi логотиби",
}

ADDRESS = {
    "ru": "Юаньхуа, г. Хайнин, провинция Чжэцзян, Китай",
    "es": "Yuanhua, Haining, provincia de Zhejiang, China",
    "de": "Yuanhua, Haining, Provinz Zhejiang, China",
    "fr": "Yuanhua, Haining, province du Zhejiang, Chine",
    "vi": "Yuanhua, Haining, tỉnh Chiết Giang, Trung Quốc",
    "ja": "中国浙江省海寧市袁花鎮",
    "uz": "Yuanhua shaharchasi, Haining shahri, Zhejiang viloyati, Xitoy",
    "kk": "Юаньхуа кенті, Хайнин қаласы, Чжэцзян провинциясы, Қытай",
    "ky": "Юаньхуа шаарчасы, Хайнин шаары, Чжэцзян провинциясы, Кытай",
}

PLACEHOLDERS = {
    "ru": {
        "e.g. Ahmed Ali": "например: Ahmed Ali",
        "e.g. ABC Water Trading LLC": "например: ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "например: +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "например: 3 000 шт. или 1 комплект",
        "e.g. Saudi Arabia": "например: Саудовская Аравия",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "например: PP 10 дюймов 5 микрон, CTO угольный блок, RO мембрана 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "например: Джебель-Али / Роттердам / Лос-Анджелес",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Укажите размер, микронность, расход, упаковку, логотип и необходимые сертификаты.",
    },
    "es": {
        "e.g. Ahmed Ali": "p. ej. Ahmed Ali",
        "e.g. ABC Water Trading LLC": "p. ej. ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "p. ej. +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "p. ej. 3.000 uds. o 1 juego",
        "e.g. Saudi Arabia": "p. ej. Arabia Saudita",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "p. ej. PP 10 pulgadas 5 micras, bloque de carbón CTO, membrana RO 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "p. ej. Jebel Ali / Rotterdam / Los Angeles",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Indique tamaño, micraje, caudal, embalaje, logotipo y certificados necesarios.",
    },
    "de": {
        "e.g. Ahmed Ali": "z. B. Ahmed Ali",
        "e.g. ABC Water Trading LLC": "z. B. ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "z. B. +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "z. B. 3.000 Stk. oder 1 Set",
        "e.g. Saudi Arabia": "z. B. Saudi-Arabien",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "z. B. PP 10 Zoll 5 Mikron, CTO-Kohlenstoffblock, RO-Membran 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "z. B. Jebel Ali / Rotterdam / Los Angeles",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Bitte Größe, Mikronwert, Durchfluss, Verpackung, Logo und benötigte Zertifikate angeben.",
    },
    "fr": {
        "e.g. Ahmed Ali": "ex. Ahmed Ali",
        "e.g. ABC Water Trading LLC": "ex. ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "ex. +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "ex. 3 000 pièces ou 1 jeu",
        "e.g. Saudi Arabia": "ex. Arabie saoudite",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "ex. PP 10 pouces 5 microns, bloc charbon CTO, membrane RO 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "ex. Jebel Ali / Rotterdam / Los Angeles",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Indiquez la taille, le micronnage, le débit, l'emballage, le logo et les certificats requis.",
    },
    "vi": {
        "e.g. Ahmed Ali": "ví dụ: Ahmed Ali",
        "e.g. ABC Water Trading LLC": "ví dụ: ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "ví dụ: +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "ví dụ: 3.000 chiếc hoặc 1 bộ",
        "e.g. Saudi Arabia": "ví dụ: Ả Rập Xê Út",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "ví dụ: PP 10 inch 5 micron, lõi CTO carbon block, màng RO 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "ví dụ: Jebel Ali / Rotterdam / Los Angeles",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Vui lòng ghi rõ kích thước, micron, lưu lượng, bao bì, logo và chứng chỉ cần thiết.",
    },
    "ja": {
        "e.g. Ahmed Ali": "例：Ahmed Ali",
        "e.g. ABC Water Trading LLC": "例：ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "例：+971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "例：3,000個または1セット",
        "e.g. Saudi Arabia": "例：サウジアラビア",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "例：PP 10インチ 5ミクロン、CTOカーボンブロック、RO膜400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "例：Jebel Ali / Rotterdam / Los Angeles",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "サイズ、ミクロン精度、流量、包装、ロゴ、必要な証明書をご記入ください。",
    },
    "uz": {
        "e.g. Ahmed Ali": "masalan: Ahmed Ali",
        "e.g. ABC Water Trading LLC": "masalan: ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "masalan: +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "masalan: 3 000 dona yoki 1 to‘plam",
        "e.g. Saudi Arabia": "masalan: Saudiya Arabistoni",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "masalan: PP 10 dyuym 5 mikron, CTO karbon blok, RO membrana 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "masalan: Jebel Ali / Rotterdam / Los Angeles",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "O‘lcham, mikron darajasi, oqim, qadoqlash, logo va kerakli sertifikatlarni yozing.",
    },
    "kk": {
        "e.g. Ahmed Ali": "мысалы: Ahmed Ali",
        "e.g. ABC Water Trading LLC": "мысалы: ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "мысалы: +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "мысалы: 3 000 дана немесе 1 жиынтық",
        "e.g. Saudi Arabia": "мысалы: Сауд Арабиясы",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "мысалы: PP 10 дюйм 5 микрон, CTO көмір блогы, RO мембрана 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "мысалы: Джебель-Али / Роттердам / Лос-Анджелес",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Өлшемді, микрон деңгейін, ағынды, қаптаманы, логотипті және қажет сертификаттарды көрсетіңіз.",
    },
    "ky": {
        "e.g. Ahmed Ali": "мисалы: Ahmed Ali",
        "e.g. ABC Water Trading LLC": "мисалы: ABC Water Trading LLC",
        "e.g. +971 50 123 4567": "мисалы: +971 50 123 4567",
        "e.g. 3,000 pcs or 1 set": "мисалы: 3 000 даана же 1 топтом",
        "e.g. Saudi Arabia": "мисалы: Сауд Арабиясы",
        "e.g. PP 10 inch 5 micron, CTO carbon block, RO membrane 400G": "мисалы: PP 10 дюйм 5 микрон, CTO көмүр блогу, RO мембрана 400G",
        "e.g. Jebel Ali / Rotterdam / Los Angeles": "мисалы: Джебель-Али / Роттердам / Лос-Анджелес",
        "Please include size, micron rating, flow rate, packaging, logo and certificates needed.": "Өлчөмдү, микрон деңгээлин, агымды, таңгакты, логотипти жана керектүү сертификаттарды жазыңыз.",
    },
}

ALT_PHRASES = {
    "ru": {
        " - side view for under sink installation": " - вид сбоку для установки под мойкой",
        " - white front view with digital display": " - белый вид спереди с цифровым дисплеем",
        " - compact cabinet main product view": " - основной вид компактного корпуса",
        " - white front cabinet view": " - белый корпус спереди",
        " - built-in pressure tank internal layout": " - внутренняя компоновка со встроенным баком",
        " - five stage RO filtration configuration": " - конфигурация пятиступенчатой RO-фильтрации",
        " - six stage RO filtration configuration": " - конфигурация шестиступенчатой RO-фильтрации",
        " - black angled cabinet view": " - черный корпус под углом",
        " - black front display view": " - черный корпус спереди с дисплеем",
        " - black rear water connection ports": " - задние порты подключения воды на черном корпусе",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Линия производства CTO угольных блок-фильтров с активированным углем из кокосовой скорлупы",
        "Inline water filter cartridge quick connect assembly line": "Линия сборки быстросъемных inline-картриджей для водяных фильтров",
        "Water filter pressure and leakage quality control test before shipment": "Контроль давления и герметичности водяных фильтров перед отгрузкой",
    },
    "es": {
        " - side view for under sink installation": " - vista lateral para instalación bajo fregadero",
        " - white front view with digital display": " - vista frontal blanca con pantalla digital",
        " - compact cabinet main product view": " - vista principal del gabinete compacto",
        " - white front cabinet view": " - vista frontal del gabinete blanco",
        " - built-in pressure tank internal layout": " - distribución interna con tanque integrado",
        " - five stage RO filtration configuration": " - configuración de filtración RO de cinco etapas",
        " - six stage RO filtration configuration": " - configuración de filtración RO de seis etapas",
        " - black angled cabinet view": " - vista angular del gabinete negro",
        " - black front display view": " - vista frontal negra con pantalla",
        " - black rear water connection ports": " - puertos traseros de conexión de agua del gabinete negro",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Línea de producción de filtro CTO de bloque de carbón con carbón activado de cáscara de coco",
        "Inline water filter cartridge quick connect assembly line": "Línea de ensamblaje de cartuchos de filtro de agua en línea con conexión rápida",
        "Water filter pressure and leakage quality control test before shipment": "Prueba de presión y fugas del filtro de agua antes del envío",
    },
    "de": {
        " - side view for under sink installation": " - Seitenansicht für Untertischmontage",
        " - white front view with digital display": " - weiße Frontansicht mit Digitalanzeige",
        " - compact cabinet main product view": " - Hauptansicht des kompakten Gehäuses",
        " - white front cabinet view": " - Vorderansicht des weißen Gehäuses",
        " - built-in pressure tank internal layout": " - Innenaufbau mit integriertem Drucktank",
        " - five stage RO filtration configuration": " - Konfiguration der 5-stufigen RO-Filtration",
        " - six stage RO filtration configuration": " - Konfiguration der 6-stufigen RO-Filtration",
        " - black angled cabinet view": " - schwarzes Gehäuse in Schrägansicht",
        " - black front display view": " - schwarze Frontansicht mit Display",
        " - black rear water connection ports": " - rückseitige Wasseranschlüsse am schwarzen Gehäuse",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Produktionslinie für CTO-Kohlenstoffblockfilter mit Aktivkohle aus Kokosnussschale",
        "Inline water filter cartridge quick connect assembly line": "Montagelinie für Inline-Wasserfilterkartuschen mit Schnellanschluss",
        "Water filter pressure and leakage quality control test before shipment": "Druck- und Dichtheitsprüfung von Wasserfiltern vor dem Versand",
    },
    "fr": {
        " - side view for under sink installation": " - vue latérale pour installation sous évier",
        " - white front view with digital display": " - vue avant blanche avec affichage numérique",
        " - compact cabinet main product view": " - vue principale du boîtier compact",
        " - white front cabinet view": " - vue avant du boîtier blanc",
        " - built-in pressure tank internal layout": " - agencement interne avec réservoir intégré",
        " - five stage RO filtration configuration": " - configuration de filtration RO en cinq étapes",
        " - six stage RO filtration configuration": " - configuration de filtration RO en six étapes",
        " - black angled cabinet view": " - vue en angle du boîtier noir",
        " - black front display view": " - vue avant noire avec écran",
        " - black rear water connection ports": " - ports arrière de raccordement d'eau du boîtier noir",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Ligne de production de filtre bloc de charbon CTO avec charbon actif de coque de noix de coco",
        "Inline water filter cartridge quick connect assembly line": "Ligne d'assemblage de cartouches de filtre à eau inline à raccord rapide",
        "Water filter pressure and leakage quality control test before shipment": "Contrôle de pression et d'étanchéité des filtres à eau avant expédition",
    },
    "vi": {
        " - side view for under sink installation": " - góc bên cho lắp đặt dưới bồn rửa",
        " - white front view with digital display": " - mặt trước màu trắng với màn hình kỹ thuật số",
        " - compact cabinet main product view": " - hình chính của vỏ máy nhỏ gọn",
        " - white front cabinet view": " - mặt trước vỏ màu trắng",
        " - built-in pressure tank internal layout": " - bố trí bên trong với bình áp tích hợp",
        " - five stage RO filtration configuration": " - cấu hình lọc RO năm cấp",
        " - six stage RO filtration configuration": " - cấu hình lọc RO sáu cấp",
        " - black angled cabinet view": " - góc nhìn nghiêng vỏ màu đen",
        " - black front display view": " - mặt trước màu đen có màn hình",
        " - black rear water connection ports": " - cổng kết nối nước phía sau vỏ màu đen",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Dây chuyền sản xuất lõi CTO carbon block với than hoạt tính gáo dừa",
        "Inline water filter cartridge quick connect assembly line": "Dây chuyền lắp ráp lõi lọc nước inline nối nhanh",
        "Water filter pressure and leakage quality control test before shipment": "Kiểm tra áp suất và rò rỉ của bộ lọc nước trước khi xuất hàng",
    },
    "ja": {
        " - side view for under sink installation": " - シンク下設置用の側面ビュー",
        " - white front view with digital display": " - デジタル表示付き白色正面ビュー",
        " - compact cabinet main product view": " - コンパクト筐体のメインビュー",
        " - white front cabinet view": " - 白色筐体の正面ビュー",
        " - built-in pressure tank internal layout": " - 内蔵圧力タンクの内部レイアウト",
        " - five stage RO filtration configuration": " - 5段ROろ過構成",
        " - six stage RO filtration configuration": " - 6段ROろ過構成",
        " - black angled cabinet view": " - 黒色筐体の斜めビュー",
        " - black front display view": " - ディスプレイ付き黒色正面ビュー",
        " - black rear water connection ports": " - 黒色筐体背面の給水接続ポート",
        "CTO carbon block filter production line with coconut shell activated carbon media": "ヤシ殻活性炭を使用したCTOカーボンブロックフィルター生産ライン",
        "Inline water filter cartridge quick connect assembly line": "クイック接続式インライン浄水カートリッジ組立ライン",
        "Water filter pressure and leakage quality control test before shipment": "出荷前の浄水フィルター圧力・漏れ品質検査",
    },
    "uz": {
        " - side view for under sink installation": " - rakovina ostiga o‘rnatish uchun yon ko‘rinish",
        " - white front view with digital display": " - raqamli displeyli oq old ko‘rinish",
        " - compact cabinet main product view": " - ixcham korpusning asosiy ko‘rinishi",
        " - white front cabinet view": " - oq korpusning old ko‘rinishi",
        " - built-in pressure tank internal layout": " - ichki bosim baki joylashuvi",
        " - five stage RO filtration configuration": " - besh bosqichli RO filtrlash konfiguratsiyasi",
        " - six stage RO filtration configuration": " - olti bosqichli RO filtrlash konfiguratsiyasi",
        " - black angled cabinet view": " - qora korpusning burchakdan ko‘rinishi",
        " - black front display view": " - displeyli qora old ko‘rinish",
        " - black rear water connection ports": " - qora korpusning orqa suv ulanish portlari",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Kokos qobig‘i faollashtirilgan ko‘mirli CTO karbon blok filtri ishlab chiqarish liniyasi",
        "Inline water filter cartridge quick connect assembly line": "Tez ulanishli inline suv filtri kartridjini yig‘ish liniyasi",
        "Water filter pressure and leakage quality control test before shipment": "Jo‘natishdan oldin suv filtri bosimi va sizib chiqish sifat nazorati",
    },
    "kk": {
        " - side view for under sink installation": " - раковина астына орнатуға арналған қырынан көрініс",
        " - white front view with digital display": " - цифрлық дисплейі бар ақ түсті алдыңғы көрініс",
        " - compact cabinet main product view": " - ықшам корпустың негізгі көрінісі",
        " - white front cabinet view": " - ақ корпустың алдыңғы көрінісі",
        " - built-in pressure tank internal layout": " - кіріктірілген қысым багының ішкі орналасуы",
        " - five stage RO filtration configuration": " - бес сатылы RO сүзу конфигурациясы",
        " - six stage RO filtration configuration": " - алты сатылы RO сүзу конфигурациясы",
        " - black angled cabinet view": " - қара корпустың бұрыштан көрінісі",
        " - black front display view": " - дисплейі бар қара алдыңғы көрініс",
        " - black rear water connection ports": " - қара корпустың артқы су қосылым порттары",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Кокос қабығынан алынған белсендірілген көмірі бар CTO көмір блок сүзгісінің өндіріс желісі",
        "Inline water filter cartridge quick connect assembly line": "Жылдам қосылатын inline су сүзгі картриджін құрастыру желісі",
        "Water filter pressure and leakage quality control test before shipment": "Жөнелту алдында су сүзгісінің қысым және ағып кету сапасын бақылау",
    },
    "ky": {
        " - side view for under sink installation": " - раковина астына орнотуу үчүн каптал көрүнүш",
        " - white front view with digital display": " - санарип дисплейи бар ак алдыңкы көрүнүш",
        " - compact cabinet main product view": " - ықчам корпустун негизги көрүнүшү",
        " - white front cabinet view": " - ак корпустун алдыңкы көрүнүшү",
        " - built-in pressure tank internal layout": " - ички басым багынын ички жайгашуусу",
        " - five stage RO filtration configuration": " - беш баскычтуу RO чыпкалоо конфигурациясы",
        " - six stage RO filtration configuration": " - алты баскычтуу RO чыпкалоо конфигурациясы",
        " - black angled cabinet view": " - кара корпустун бурчтан көрүнүшү",
        " - black front display view": " - дисплейи бар кара алдыңкы көрүнүш",
        " - black rear water connection ports": " - кара корпустун арткы суу туташуу порттору",
        "CTO carbon block filter production line with coconut shell activated carbon media": "Кокос кабыгынан активдештирилген көмүрү бар CTO көмүр блок сүзгү өндүрүш линиясы",
        "Inline water filter cartridge quick connect assembly line": "Inline суу чыпка картриджинин тез туташтыруучу чогултуу линиясы",
        "Water filter pressure and leakage quality control test before shipment": "Жөнөтүүдөн мурун суу чыпкасынын басым жана агып кетүү сапат көзөмөлү",
    },
}

VISIBLE_PHRASES = {
    "ru": {
        "Common B2B buyer questions": "Частые вопросы B2B-покупателей",
        "Which products are suitable for distributors?": "Какие продукты подходят для дистрибьюторов?",
        "What certification documents are available?": "Какие сертификационные документы доступны?",
        "Information We Collect": "Какие данные мы собираем",
        "Form Delivery": "Отправка формы",
        "Cookies And Analytics": "Cookie и аналитика",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Сайт может использовать базовые аналитические или защитные инструменты для оценки работы страниц и снижения спама. При добавлении дополнительных инструментов отслеживания необходимо пересмотреть настройки уведомления о cookie с учетом GDPR и других региональных требований.",
        "Your Rights": "Ваши права",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Вы можете запросить исправление или удаление данных запроса по адресу expresswater025@gmail.com или через WhatsApp отдела продаж: +86-19908311885.",
        "Industrial RO Machine": "Промышленная RO-машина",
    },
    "es": {
        "Common B2B buyer questions": "Preguntas frecuentes de compradores B2B",
        "Which products are suitable for distributors?": "¿Qué productos son adecuados para distribuidores?",
        "What certification documents are available?": "¿Qué documentos de certificación están disponibles?",
        "Information We Collect": "Información que recopilamos",
        "Form Delivery": "Envío del formulario",
        "Cookies And Analytics": "Cookies y analítica",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "El sitio web puede utilizar herramientas básicas de analítica o seguridad para entender el rendimiento de las páginas y reducir el spam. Si se añaden herramientas adicionales de seguimiento, la configuración del aviso de cookies debe revisarse según el GDPR y otros requisitos regionales.",
        "Your Rights": "Sus derechos",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Puede solicitar la corrección o eliminación de la información de su consulta escribiendo a expresswater025@gmail.com o contactando con ventas por WhatsApp al +86-19908311885.",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 pcs/month.": "Filtros de sedimento multicapa unidos térmicamente: 0,5 a 50 µm. Capacidad: 200.000 uds./mes.",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 uds./month.": "Filtros de sedimento multicapa unidos térmicamente: 0,5 a 50 µm. Capacidad: 200.000 uds./mes.",
        "Industrial RO Machine": "Máquina RO industrial",
    },
    "de": {
        "Common B2B buyer questions": "Häufige Fragen von B2B-Käufern",
        "Which products are suitable for distributors?": "Welche Produkte eignen sich für Distributoren?",
        "What certification documents are available?": "Welche Zertifizierungsunterlagen sind verfügbar?",
        "Information We Collect": "Welche Informationen wir erfassen",
        "Form Delivery": "Formularübermittlung",
        "Cookies And Analytics": "Cookies und Analyse",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Die Website kann grundlegende Analyse- oder Sicherheitstools verwenden, um die Seitenleistung zu verstehen und Spam zu reduzieren. Wenn zusätzliche Tracking-Tools ergänzt werden, sollten die Cookie-Hinweiseinstellungen gemäß DSGVO und anderen regionalen Anforderungen geprüft werden.",
        "Your Rights": "Ihre Rechte",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Sie können die Berichtigung oder Löschung Ihrer Anfrageinformationen per E-Mail an expresswater025@gmail.com oder über WhatsApp-Vertrieb unter +86-19908311885 beantragen.",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 pcs/month.": "Mehrlagige thermisch gebundene Sedimentfilter: 0,5 bis 50 µm. Kapazität: 200.000 Stück/Monat.",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 Stk./month.": "Mehrlagige thermisch gebundene Sedimentfilter: 0,5 bis 50 µm. Kapazität: 200.000 Stück/Monat.",
        "Industrial RO Machine": "Industrielle RO-Maschine",
    },
    "fr": {
        "Common B2B buyer questions": "Questions fréquentes des acheteurs B2B",
        "Which products are suitable for distributors?": "Quels produits conviennent aux distributeurs ?",
        "What certification documents are available?": "Quels documents de certification sont disponibles ?",
        "Information We Collect": "Informations que nous collectons",
        "Form Delivery": "Envoi du formulaire",
        "Cookies And Analytics": "Cookies et analyse",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Le site peut utiliser des outils de base d'analyse ou de sécurité pour comprendre les performances des pages et réduire le spam. Si des outils de suivi supplémentaires sont ajoutés, les réglages de l'avis sur les cookies doivent être révisés selon le RGPD et les autres exigences régionales.",
        "Your Rights": "Vos droits",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Vous pouvez demander la correction ou la suppression de vos informations de demande par e-mail à expresswater025@gmail.com ou via WhatsApp au +86-19908311885.",
        "Industrial RO Machine": "Machine RO industrielle",
    },
    "vi": {
        "Common B2B buyer questions": "Câu hỏi thường gặp của khách mua B2B",
        "Which products are suitable for distributors?": "Sản phẩm nào phù hợp cho nhà phân phối?",
        "What certification documents are available?": "Có thể cung cấp những tài liệu chứng nhận nào?",
        "Information We Collect": "Thông tin chúng tôi thu thập",
        "Form Delivery": "Gửi biểu mẫu",
        "Cookies And Analytics": "Cookie và phân tích",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Trang web có thể sử dụng các công cụ phân tích hoặc bảo mật cơ bản để hiểu hiệu suất trang và giảm thư rác. Nếu thêm công cụ theo dõi khác, cần xem lại thiết lập thông báo cookie theo GDPR và các yêu cầu khu vực khác.",
        "Your Rights": "Quyền của bạn",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Bạn có thể yêu cầu chỉnh sửa hoặc xóa thông tin yêu cầu bằng cách gửi email tới expresswater025@gmail.com hoặc liên hệ bộ phận bán hàng WhatsApp qua +86-19908311885.",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 pcs/month.": "Lõi lọc cặn nhiều lớp liên kết nhiệt: 0,5 đến 50 µm. Công suất: 200.000 chiếc/tháng.",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 cái/month.": "Lõi lọc cặn nhiều lớp liên kết nhiệt: 0,5 đến 50 µm. Công suất: 200.000 chiếc/tháng.",
        "Industrial RO Machine": "Máy RO công nghiệp",
        '"name":"Filtration Stages"': '"name":"Số cấp lọc"',
        '"name":"Output Capacity"': '"name":"Công suất đầu ra"',
        '"name":"Storage Tank"': '"name":"Bình áp"',
        '"name":"Product Type"': '"name":"Loại sản phẩm"',
        "Dây chuyền sản xuất lõi CTO carbon block với than hoạt tính gáo dừa": "Dây chuyền sản xuất lõi CTO than khối với than hoạt tính gáo dừa",
        "Với đơn hàng lõi carbon block, Yuchen Water kiểm soát công thức, trộn, nạp khuôn, ép, nung kết, cắt và đóng gói để giữ phân bố lỗ rỗng, độ bền, khả năng giảm clo và kích thước OEM ổn định cho khách hàng B2B.": "Với đơn hàng lõi than khối, Yuchen Water kiểm soát công thức, trộn, nạp khuôn, ép, nung kết, cắt và đóng gói để giữ phân bố lỗ rỗng, độ bền, khả năng giảm clo và kích thước OEM ổn định cho khách hàng B2B.",
        "Trong sản xuất, nhân viên theo dõi nhiệt độ, tần số, áp lực và khối lượng nạp. Các kiểm soát này giúp dây chuyền carbon block chạy ổn định cho đơn hàng lõi lọc nước OEM.": "Trong sản xuất, nhân viên theo dõi nhiệt độ, tần số, áp lực và khối lượng nạp. Các kiểm soát này giúp dây chuyền lõi than khối chạy ổn định cho đơn hàng lõi lọc nước OEM.",
        "Hiệu suất carbon block điển hình": "Hiệu suất lõi than khối điển hình",
        "Có các cấp lọc danh nghĩa 0.5, 1, 5 và 10 micron với khả năng giữ bẩn cao. Carbon hoạt tính gáo dừa giúp giảm clo, vị, mùi và VOCs, giữ sụt áp thấp, hạn chế bột carbon và là lựa chọn kinh tế so với carbon block ép đùn.": "Có các cấp lọc danh nghĩa 0.5, 1, 5 và 10 micron với khả năng giữ bẩn cao. Than hoạt tính gáo dừa giúp giảm clo, vị, mùi và hợp chất hữu cơ bay hơi, giữ sụt áp thấp, hạn chế bột than và là lựa chọn kinh tế so với lõi than ép đùn.",
        "Khi dự án cần hồ sơ, vật liệu hoặc sản phẩm chọn lọc có thể được xác nhận hoặc thử nghiệm theo yêu cầu WQA và NSF/ANSI 42 nếu phù hợp và được xác nhận trong đơn hàng. Khách OEM có thể tùy chỉnh OD, ID, chiều dài, hình dạng, nhãn logo và bao bì. Carbon hoạt tính gáo dừa có thể đạt iodine trên 1000 và hấp phụ xanh methylene trên 120 khi được chỉ định.": "Khi dự án cần hồ sơ, vật liệu hoặc sản phẩm chọn lọc có thể được xác nhận hoặc thử nghiệm theo yêu cầu WQA và NSF/ANSI 42 nếu phù hợp và được xác nhận trong đơn hàng. Khách OEM có thể tùy chỉnh OD, ID, chiều dài, hình dạng, nhãn biểu trưng và bao bì. Than hoạt tính gáo dừa có thể đạt chỉ số i-ốt trên 1000 và hấp phụ xanh metylen trên 120 khi được chỉ định.",
    },
    "ja": {
        "Common B2B buyer questions": "B2Bバイヤーからよくある質問",
        "Which products are suitable for distributors?": "販売代理店に適した製品はどれですか？",
        "What certification documents are available?": "どの認証関連書類を提供できますか？",
        "Information We Collect": "収集する情報",
        "Form Delivery": "フォーム送信",
        "Cookies And Analytics": "Cookieとアクセス解析",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "本サイトでは、ページのパフォーマンス把握とスパム低減のため、基本的な解析またはセキュリティツールを使用する場合があります。追加の追跡ツールを導入する場合は、GDPRその他地域要件に合わせてCookie通知設定を確認します。",
        "Your Rights": "お客様の権利",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "お問い合わせ情報の訂正または削除は、expresswater025@gmail.com へのメール、または +86-19908311885 のWhatsApp営業窓口までご連絡ください。",
        "Multi-layer thermally-bonded sediment filters: 0.5 to 50 µm. Capacity: 200,000 個/month.": "熱接着式の多層沈殿物フィルターで、0.5〜50µmの仕様に対応します。生産能力：月間200,000個。",
        "VOCs": "揮発性有機化合物",
        "RO Seawater Desalination Equipment": "RO海水淡水化装置",
        "産業用フィルター RO Manufacturer": "RO海水淡水化装置",
        "Industrial RO Machine": "産業用RO装置",
        '"name":"Filtration Stages"': '"name":"ろ過段数"',
        '"name":"Output Capacity"': '"name":"処理能力"',
        '"name":"Storage Tank"': '"name":"貯水タンク"',
        '"name":"Product Type"': '"name":"製品タイプ"',
        '"name":"Material"': '"name":"材質"',
        '"name":"Size"': '"name":"サイズ"',
        '"name":"Application"': '"name":"用途"',
        '"name":"Capacity"': '"name":"処理能力"',
        '"name":"Pretreatment"': '"name":"前処理"',
        "5, 6 or 7 stage RO water purifier": "5段・6段・7段RO浄水器",
        "Food-grade plastic housings, plastic or metal bracket, optional pressure gauges": "食品接触対応樹脂ハウジング、樹脂または金属ブラケット、圧力計オプション",
        "Customized by bracket, backboard and filter stage configuration": "ブラケット、背板、ろ過段数構成に応じてカスタマイズ",
        "RO water purifier, water dispenser, pre-filtration system, commercial water treatment and replacement cartridge market": "RO浄水器、ウォーターディスペンサー、前処理システム、業務用水処理、交換カートリッジ市場",
        "Logo, label, packaging, bracket, backboard, filter stage and color customization": "ロゴ、ラベル、包装、ブラケット、背板、ろ過段数、色のカスタマイズ",
        "Confirm by configuration, packaging and customization level": "構成、包装、カスタマイズ内容により確認",
        "RO seawater desalination equipment and industrial RO machine": "RO海水淡水化装置および産業用RO装置",
        "1T, 2T, 3T, 5T per hour or larger custom capacity": "1T、2T、3T、5T/時、またはより大きいカスタム処理能力",
        "Stainless steel frame, FRP or stainless tanks, PVC piping, RO membrane housings and industrial control parts": "ステンレスフレーム、FRPまたはステンレスタンク、PVC配管、RO膜ハウジング、産業用制御部品",
        "Quartz sand filter, activated carbon filter, softener, precision/security filter and dosing system": "石英砂ろ過器、活性炭ろ過器、軟水器、精密・保安フィルター、薬注システム",
        "Seawater desalination, brackish water treatment, commercial water treatment and industrial process water": "海水淡水化、汽水処理、商業用水処理、産業プロセス水",
        "Capacity, tank count, valve brand, pump, membrane, voltage, control panel, logo and packaging": "処理能力、タンク数、バルブブランド、ポンプ、膜、電圧、制御盤、ロゴ、包装",
        "Project based; confirm by capacity, component list and customization level": "案件ごとに処理能力、部品リスト、カスタマイズ内容で確認",
    },
    "uz": {
        "Common B2B buyer questions": "B2B xaridorlarning keng tarqalgan savollari",
        "Which products are suitable for distributors?": "Distribyutorlar uchun qaysi mahsulotlar mos?",
        "What certification documents are available?": "Qaysi sertifikat hujjatlari mavjud?",
        "Information We Collect": "Biz to‘playdigan ma’lumotlar",
        "Form Delivery": "Formani yuborish",
        "Cookies And Analytics": "Cookie fayllari va analitika",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Sayt sahifa ishlashini tushunish va spamni kamaytirish uchun asosiy analitika yoki xavfsizlik vositalaridan foydalanishi mumkin. Qo‘shimcha kuzatuv vositalari qo‘shilsa, cookie xabarnomasi sozlamalari GDPR va boshqa mintaqaviy talablar bo‘yicha qayta ko‘rib chiqilishi kerak.",
        "Your Rights": "Sizning huquqlaringiz",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "So‘rov ma’lumotlarini tuzatish yoki o‘chirishni expresswater025@gmail.com manziliga yozib yoki +86-19908311885 WhatsApp savdo bo‘limi orqali so‘rashingiz mumkin.",
        "RO Seawater Desalination Equipment": "RO dengiz suvini chuchuklashtirish uskunasi",
        "Sanoat filtri RO Manufacturer": "RO dengiz suvini chuchuklashtirish uskunasi",
        "Industrial RO Machine": "Sanoat RO uskunasi",
        "PP Melt BlownF Polypropylene Fiber Cartridge": "PP melt blown polipropilen tolali kartrij",
        "Yuchen Water protects buyer inquiry information and uses submitted data only to respond to OEM/ODM water filtration requests.": "Yuchen Water xaridor so‘rovi ma’lumotlarini himoya qiladi va yuborilgan ma’lumotlardan faqat OEM/ODM suv filtrlash so‘rovlariga javob berish uchun foydalanadi.",
        "When you send an inquiry, we may collect your name, company, email address, WhatsApp number, country, product requirements, quantity, destination port and message details.": "So‘rov yuborganingizda ism, kompaniya, email manzili, WhatsApp raqami, mamlakat, mahsulot talablari, miqdor, manzil porti va xabar tafsilotlari yig‘ilishi mumkin.",
        "We use inquiry information to prepare quotations, confirm specifications, arrange samples, discuss shipping and follow up with technical or sales support. We do not sell buyer contact information.": "Biz so‘rov ma’lumotlaridan narx taklifi tayyorlash, spetsifikatsiyani tasdiqlash, namunalarni kelishish, yetkazib berishni muhokama qilish va texnik yoki savdo yordami bilan bog‘lanish uchun foydalanamiz. Xaridor aloqa ma’lumotlarini sotmaymiz.",
        "Inquiry forms are configured to send submissions to expresswater025@gmail.com. After a successful submission, the page shows a thank-you message so buyers know the request has been sent.": "So‘rov shakllari yuborilgan ma’lumotlarni expresswater025@gmail.com manziliga yetkazishga sozlangan. Muvaffaqiyatli yuborilgandan keyin sahifada rahmat xabari ko‘rsatiladi, shunda xaridor so‘rov yuborilganini biladi.",
        "Tijorat RO tizimi oldindan tozalash, xavfsizlik filtri, RO membrana, yuqori bosimli nasos, manometrlar, klapanlar, elektr boshqaruv va himoya qurilmalarini o‘z ichiga olishi mumkin. Xom suv sifatiga qarab quartz sand filter, activated carbon filter, yumshatish baki, FRP yoki zanglamas baklar va TDS o‘lchagich tanlanadi.": "Tijorat RO tizimi oldindan tozalash, xavfsizlik filtri, RO membrana, yuqori bosimli nasos, manometrlar, klapanlar, elektr boshqaruv va himoya qurilmalarini o‘z ichiga olishi mumkin. Xom suv sifatiga qarab kvars qum filtri, faol uglerod filtri, yumshatish baki, FRP yoki zanglamas baklar va TDS o‘lchagich tanlanadi.",
        "Uskunani tekis, toza va drenajli yopiq polga o‘rnating. Cartridge almashtirish, valve service, membrane chiqarish va elektr tekshiruvi uchun joy qoldiring. Kirish suvi, drenaj va mahsulot suvi quvurlari oqim yo‘nalishiga mos ulanadi, kuchlanish esa nameplate qiymatiga mos bo‘lishi kerak.": "Uskunani tekis, toza va drenajli yopiq polga o‘rnating. Kartrijlarni almashtirish, klapanlarga xizmat ko‘rsatish, membranani chiqarish va elektr tekshiruvi uchun joy qoldiring. Kirish suvi, drenaj va mahsulot suvi quvurlari oqim yo‘nalishiga mos ulanadi, kuchlanish esa uskunadagi yorliq qiymatiga mos bo‘lishi kerak.",
        "Birinchi ishga tushirishdan oldin old filtrlari va xavfsizlik filtrini suv tiniq bo‘lguncha yuving. Housing ichidagi havoni chiqaring, barcha ulanishlarda sizib chiqish bor-yo‘qligini tekshiring, so‘ng pump va RO machine ni control panel tartibi bo‘yicha ishga tushiring. Commissioning vaqtida pressure, flow va TDS ni yozib boring.": "Birinchi ishga tushirishdan oldin old filtrlari va xavfsizlik filtrini suv tiniq bo‘lguncha yuving. Korpus ichidagi havoni chiqaring, barcha ulanishlarda sizib chiqish bor-yo‘qligini tekshiring, so‘ng nasos va RO uskunasini boshqaruv paneli tartibi bo‘yicha ishga tushiring. Ishga tushirish sinovi vaqtida bosim, oqim va TDS ni yozib boring.",
        "Operator inlet pressure, pump pressure, product water flow, concentrate flow, TDS, tebranish, shovqin va sizib chiqishni kuzatishi kerak. Low pressure, dry-running risk, beqaror voltage yoki water quality keskin o‘zgarsa, tizimni to‘xtatib sababini tekshiring.": "Operator kirish bosimi, nasos bosimi, toza suv oqimi, konsentrat oqimi, TDS, tebranish, shovqin va sizib chiqishni kuzatishi kerak. Past bosim, quruq ishlash xavfi, beqaror kuchlanish yoki suv sifati keskin o‘zgarsa, tizimni to‘xtatib sababini tekshiring.",
        "Low flow, high TDS, leakage, pump fault yoki automatic shutdown bo‘lsa, water supply, pre-filter, cartridges, valves, membrane fouling va electrical protection ni tekshiring. Yuchen Water bilan bog‘langanda model, voltage, photos, short video, water analysis va operating data yuboring.": "Past oqim, yuqori TDS, sizib chiqish, nasos nosozligi yoki avtomatik o‘chish bo‘lsa, suv ta’minoti, old filtr, kartrijlar, klapanlar, membrana ifloslanishi va elektr himoyasini tekshiring. Yuchen Water bilan bog‘langanda model, kuchlanish, fotosuratlar, qisqa video, suv tahlili va ishlash ma’lumotlarini yuboring.",
        "Ommaviy ishlab chiqarishdan oldin namunalar kompaniya standarti yoki mijoz talabi bo‘yicha tasdiqlanadi: formula, sinterlash vaqti, harorat, aeratsiya testi va takroriy bosim sikli testi. Ishlab chiqarishda harorat, chastota, bosim va to‘ldirish og‘irligi kuzatiladi. Tayyor cartridge-lar batch sampling yoki to‘liq inspeksiya bilan nuqson, yoriq, og‘irlik, pressure drop va filtratsiya ko‘rsatkichlari bo‘yicha tekshiriladi. 0.5, 1, 5 va 10 mikron, yuqori kir tutish quvvati, xlor, ta’m, hid va VOCs kamaytirish, past pressure drop va carbon fines chiqarmaslik mavjud. Buyurtmada tasdiqlansa, tanlangan materiallar yoki mahsulotlar WQA va NSF/ANSI 42 bo‘yicha sinovdan o‘tkazilishi mumkin; OD, ID, uzunlik, shakl, logo label, packaging, iodine value 1000dan yuqori va methylene blue adsorption 120dan yuqori ko‘rsatilishi mumkin.": "Ommaviy ishlab chiqarishdan oldin namunalar kompaniya standarti yoki mijoz talabi bo‘yicha tasdiqlanadi: retseptura, sinterlash vaqti, harorat, aeratsiya sinovi va takroriy bosim sikli sinovi. Ishlab chiqarishda harorat, chastota, bosim va to‘ldirish og‘irligi kuzatiladi. Tayyor kartrijlar partiyadan namuna olish yoki to‘liq inspeksiya orqali nuqson, yoriq, og‘irlik, bosim yo‘qotilishi va filtrlash ko‘rsatkichlari bo‘yicha tekshiriladi. 0.5, 1, 5 va 10 mikron, yuqori kir tutish quvvati, xlor, ta’m, hid va uchuvchi organik birikmalarni kamaytirish, past bosim yo‘qotilishi va ko‘mir kukuni chiqarmaslik xususiyatlari mavjud. Buyurtmada tasdiqlansa, tanlangan materiallar yoki mahsulotlar WQA va NSF/ANSI 42 bo‘yicha sinovdan o‘tkazilishi mumkin; OD, ID, uzunlik, shakl, logotip yorlig‘i, qadoqlash, yod ko‘rsatkichi 1000dan yuqori va metilen ko‘ki adsorbsiyasi 120dan yuqori ko‘rsatilishi mumkin.",
    },
    "kk": {
        "Common B2B buyer questions": "B2B сатып алушылардың жиі қойылатын сұрақтары",
        "Which products are suitable for distributors?": "Дистрибьюторлар үшін қай өнімдер қолайлы?",
        "What certification documents are available?": "Қандай сертификат құжаттары қолжетімді?",
        "Information We Collect": "Біз жинайтын ақпарат",
        "Form Delivery": "Форманы жіберу",
        "Cookies And Analytics": "Cookie файлдары және аналитика",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Сайт беттердің жұмысын түсіну және спамды азайту үшін негізгі аналитика немесе қауіпсіздік құралдарын қолдануы мүмкін. Қосымша бақылау құралдары қосылса, cookie ескерту параметрлері GDPR және басқа өңірлік талаптарға сай қайта қаралуы керек.",
        "Your Rights": "Сіздің құқықтарыңыз",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Сұрау ақпаратыңызды түзету немесе жою үшін expresswater025@gmail.com мекенжайына жаза аласыз немесе +86-19908311885 WhatsApp сату бөліміне хабарласа аласыз.",
        "RO Seawater Desalination Equipment": "RO теңіз суын тұщыландыру жабдығы",
        "Өнеркәсіптік сүзгі RO Manufacturer": "RO теңіз суын тұщыландыру жабдығы",
        "Industrial RO Machine": "Өнеркәсіптік RO қондырғысы",
    },
    "ky": {
        "Common B2B buyer questions": "B2B сатып алуучулардын кеңири суроолору",
        "Which products are suitable for distributors?": "Дистрибьюторлор үчүн кайсы өнүмдөр ылайыктуу?",
        "What certification documents are available?": "Кандай сертификат документтери бар?",
        "Information We Collect": "Биз чогулткан маалымат",
        "Form Delivery": "Форманы жөнөтүү",
        "Cookies And Analytics": "Cookie файлдары жана аналитика",
        "The website may use basic analytics or security tools to understand page performance and reduce spam. If additional tracking tools are added, cookie notice settings should be reviewed for GDPR and other regional requirements.": "Сайт барактардын иштешин түшүнүү жана спамды азайтуу үчүн негизги аналитика же коопсуздук куралдарын колдонушу мүмкүн. Кошумча көзөмөл куралдары кошулса, cookie эскертүүсү GDPR жана башка аймактык талаптарга ылайык кайра каралышы керек.",
        "Your Rights": "Сиздин укуктарыңыз",
        "You can request correction or deletion of your inquiry information by emailing expresswater025@gmail.com or contacting WhatsApp sales at +86-19908311885.": "Сурам маалыматыңызды оңдоону же өчүрүүнү expresswater025@gmail.com дарегине жазып же +86-19908311885 WhatsApp сатуу бөлүмү аркылуу сурай аласыз.",
        "RO Seawater Desalination Equipment": "RO деңиз суусун тузсуздандыруу жабдыгы",
        "Өнөр жай сүзгүсү RO Manufacturer": "RO деңиз суусун тузсуздандыруу жабдыгы",
        "Industrial RO Machine": "Өнөр жай RO жабдыгы",
        "PP Melt BlownF Polypropylene Fiber Cartridge": "PP melt blown полипропилен була картриджи",
        "VOCs": "учма органикалык кошулмаларды",
        "iodine value": "йод көрсөткүчү",
        "methylene blue adsorption": "метилен көгүнүн адсорбциясы",
    },
}

ADDRESS_RE = re.compile(
    r'(<div class="contact-info-item">\s*<div class="icon">📍</div>\s*<div>\s*<div class="label">.*?</div>\s*)<p>.*?</p>',
    re.S,
)


def fix_page(page: str, lang: str, filename: str) -> str:
    page = page.replace('aria-label="Select language"', f'aria-label="{SELECT_LABEL[lang]}"')
    if lang == "uz":
        page = re.sub(r"Yuchen Sanyi logotipi(?:tipi)+", LOGO_ALT[lang], page)
    page = re.sub(r"\bYuchen Sanyi logo\b", LOGO_ALT[lang], page)
    page = page.replace(" for OEM/ODM water filtration projects", "")
    for source, target in PLACEHOLDERS[lang].items():
        page = page.replace(source, target)
    for source, target in ALT_PHRASES[lang].items():
        page = page.replace(source, target)
    for source, target in VISIBLE_PHRASES[lang].items():
        page = page.replace(source, target)
    if filename == "contact.html":
        page = ADDRESS_RE.sub(rf"\1<p>{ADDRESS[lang]}</p>", page, count=1)
    return page


def main() -> None:
    changed = 0
    scanned = 0
    for lang in LANGS:
        for path in (ROOT / lang).glob("*.html"):
            scanned += 1
            original = path.read_text(encoding="utf-8", errors="ignore")
            page = fix_page(original, lang, path.name)
            if page != original:
                path.write_text(page, encoding="utf-8")
                changed += 1
    print(f"Scanned {scanned} priority-language HTML files; changed {changed} files.")


if __name__ == "__main__":
    main()
