from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]

COMMON_SOURCES = {
    "halal_about": "Halal-related documents are available upon request for qualified orders.",
    "quality_docs_short": "Quality documents available upon request · OEM/ODM",
    "quality_docs_plain": "Quality documents available upon request",
    "quality_docs_footer": "Yuchen Water · Quality documents available upon request · OEM/ODM ·",
    "quality_management": "Quality management documents available upon request.",
    "rights": "All rights reserved.",
    "cert_footer": "selected NSF/ANSI and Halal-related documents available on request",
    "privacy": "Privacy Policy",
    "success_1": "Thank you. Your inquiry has been submitted successfully and sent to Yuchen Water at expresswater025@gmail.com.",
    "success_2": "Our sales engineer will contact you as soon as possible.",
    "success_3": "You can also contact us anytime on WhatsApp +86-19908311885 or email expresswater025@gmail.com.",
    "schema_quality_name": '"name":"Quality documents"',
    "schema_quality_value": "Selected products can be supplied or tested according to NSF/ANSI 42, 53 and 58 requirements. ISO 9001, CE, SGS and Halal-related documents are available upon request by product model and market requirement.",
    "org_description": "Yuchen Water is a China water filtration manufacturer supplying PP, CTO, GAC, T33, UF, RO membrane, water purifier, water dispenser and filter housing products for global B2B OEM and ODM buyers.",
    "org_slogan": "Industrial-Grade Water Purification & OEM Solutions",
    "website_description": "Global water filter and reverse osmosis system manufacturer for OEM/ODM wholesale buyers",
    "worldwide": "Worldwide",
    "award_1": "27+ years of water filtration manufacturing experience",
    "award_2": "50+ export markets",
    "award_3": "200+ water filtration product SKU range",
    "cred_1": "Selected products can be supplied or tested according to NSF/ANSI 42, 53 and 58 requirements",
    "cred_2": "ISO 9001 quality management documents available upon request",
    "cred_3": "CE documents available upon request where applicable",
    "cred_4": "SGS test reports available upon request where applicable",
    "cred_5": "Halal-related documents available upon request where applicable",
    "cred_cat_1": "product testing support",
    "cred_cat_2": "quality document",
    "cred_cat_3": "market document",
    "cred_cat_4": "third-party test document",
    "offer_pp": "PP melt blown filter",
    "offer_cto": "CTO carbon block filter",
    "offer_gac": "GAC filter",
    "offer_t33": "T33 inline filter",
    "offer_uf": "UF membrane",
    "offer_ro": "RO membrane",
    "offer_purifier": "water purifier",
    "offer_dispenser": "water dispenser",
    "offer_housing": "filter housing",
    "offer_oem": "OEM manufacturing service",
    "offer_odm": "ODM design service",
    "faq_cert_short": "Selected products can be supplied or tested according to NSF/ANSI requirements. ISO 9001, CE, SGS and Halal-related documents are available upon request.",
    "faq_cert_tail": "ISO 9001, CE, SGS and Halal-related documents are available upon request.",
    "cat_q1": "Can this category be supplied with private-label packaging?",
    "cat_a1": "Yes. Yuchen Water supports product labels, sealed bags, color boxes, instruction sheets, master cartons and pallet marks for OEM/ODM orders.",
    "cat_q2": "What information is needed for a quotation?",
    "cat_a2": "Please send product type, target size, specification, estimated quantity, destination port and any branding or compliance requirements.",
    "cat_q3": "Are certification documents available?",
    "crumb_home": '"name":"Home"',
    "crumb_products": '"name":"Products"',
}

TRANSLATIONS = {
    "ko": {
        "halal_about": "적격 주문의 경우 Halal 관련 문서는 요청 시 제공할 수 있습니다.",
        "quality_docs_short": "품질 문서는 요청 시 제공됩니다 · OEM/ODM",
        "quality_docs_plain": "품질 문서는 요청 시 제공됩니다",
        "quality_docs_footer": "Yuchen Water · 품질 문서는 요청 시 제공됩니다 · OEM/ODM ·",
        "quality_management": "품질 관리 문서는 요청 시 제공됩니다.",
        "rights": "모든 권리 보유.",
        "cert_footer": "일부 NSF/ANSI 및 Halal 관련 문서는 요청 시 제공됩니다",
        "privacy": "개인정보 처리방침",
        "success_1": "감사합니다. 문의가 성공적으로 제출되어 Yuchen Water의 expresswater025@gmail.com 으로 전송되었습니다.",
        "success_2": "영업 엔지니어가 가능한 한 빨리 연락드리겠습니다.",
        "success_3": "언제든지 WhatsApp +86-19908311885 또는 이메일 expresswater025@gmail.com 으로도 연락하실 수 있습니다.",
        "schema_quality_name": '"name":"품질 문서"',
        "schema_quality_value": "일부 제품은 NSF/ANSI 42, 53, 58 요구사항에 따라 공급 또는 시험할 수 있습니다. ISO 9001, CE, SGS 및 Halal 관련 문서는 제품 모델과 시장 요구에 따라 요청 시 제공됩니다.",
        "org_description": "Yuchen Water는 중국 수처리 제품 제조업체로서 전 세계 B2B OEM/ODM 구매자에게 PP, CTO, GAC, T33, UF, RO 멤브레인, 정수기, 워터 디스펜서 및 필터 하우징을 공급합니다.",
        "org_slogan": "산업용 수처리 및 OEM 솔루션",
        "website_description": "OEM/ODM 도매 구매자를 위한 글로벌 정수 필터 및 RO 시스템 제조업체",
        "worldwide": "전 세계",
        "award_1": "27년 이상의 수처리 제조 경험",
        "award_2": "50개 이상의 수출 시장",
        "award_3": "200개 이상의 수처리 제품 SKU",
        "cred_1": "일부 제품은 NSF/ANSI 42, 53, 58 요구사항에 따라 공급 또는 시험할 수 있습니다",
        "cred_2": "ISO 9001 품질 관리 문서는 요청 시 제공됩니다",
        "cred_3": "해당되는 경우 CE 문서는 요청 시 제공됩니다",
        "cred_4": "해당되는 경우 SGS 시험 보고서는 요청 시 제공됩니다",
        "cred_5": "해당되는 경우 Halal 관련 문서는 요청 시 제공됩니다",
        "cred_cat_1": "제품 시험 지원",
        "cred_cat_2": "품질 문서",
        "cred_cat_3": "시장 문서",
        "cred_cat_4": "제3자 시험 문서",
        "offer_pp": "PP 멜트블로운 필터",
        "offer_cto": "CTO 카본 블록 필터",
        "offer_gac": "GAC 필터",
        "offer_t33": "T33 인라인 필터",
        "offer_uf": "UF 멤브레인",
        "offer_ro": "RO 멤브레인",
        "offer_purifier": "정수기",
        "offer_dispenser": "워터 디스펜서",
        "offer_housing": "필터 하우징",
        "offer_oem": "OEM 제조 서비스",
        "offer_odm": "ODM 설계 서비스",
        "faq_cert_short": "일부 제품은 NSF/ANSI 요구사항에 따라 공급 또는 시험할 수 있습니다. ISO 9001, CE, SGS 및 Halal 관련 문서는 요청 시 제공됩니다.",
        "faq_cert_tail": "ISO 9001, CE, SGS 및 Halal 관련 문서는 요청 시 제공됩니다.",
        "cat_q1": "이 카테고리는 자체 브랜드 포장으로 공급할 수 있습니까?",
        "cat_a1": "예. Yuchen Water는 OEM/ODM 주문을 위해 제품 라벨, 밀봉 봉투, 컬러 박스, 설명서, 마스터 카톤 및 팔레트 표시를 지원합니다.",
        "cat_q2": "견적을 받으려면 어떤 정보가 필요합니까?",
        "cat_a2": "제품 유형, 목표 크기, 사양, 예상 수량, 도착항, 브랜딩 또는 규정 요구사항을 보내 주세요.",
        "cat_q3": "인증 문서를 제공할 수 있습니까?",
        "crumb_home": '"name":"홈"',
        "crumb_products": '"name":"제품"',
    },
    "it": {
        "halal_about": "I documenti relativi Halal sono disponibili su richiesta per ordini qualificati.",
        "quality_docs_short": "Documenti qualità disponibili su richiesta · OEM/ODM",
        "quality_docs_plain": "Documenti qualità disponibili su richiesta",
        "quality_docs_footer": "Yuchen Water · documenti qualità disponibili su richiesta · OEM/ODM ·",
        "quality_management": "Documenti di gestione qualità disponibili su richiesta.",
        "rights": "Tutti i diritti riservati.",
        "cert_footer": "documenti ISO 9001, CE, SGS, NSF/ANSI selezionati e relativi Halal disponibili su richiesta",
        "privacy": "Informativa sulla privacy",
        "success_1": "Grazie. La tua richiesta è stata inviata correttamente a Yuchen Water all'indirizzo expresswater025@gmail.com.",
        "success_2": "Il nostro ingegnere commerciale ti contatterà il prima possibile.",
        "success_3": "Puoi anche contattarci in qualsiasi momento su WhatsApp +86-19908311885 o via email expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Documenti qualità"',
        "schema_quality_value": "Alcuni prodotti possono essere forniti o testati secondo i requisiti NSF/ANSI 42, 53 e 58. Documenti ISO 9001, CE, SGS e relativi Halal sono disponibili su richiesta in base al modello e al mercato.",
        "org_description": "Yuchen Water è un produttore cinese di prodotti per la filtrazione dell'acqua che fornisce PP, CTO, GAC, T33, UF, membrane RO, purificatori d'acqua, dispenser e alloggiamenti filtro per acquirenti B2B OEM/ODM globali.",
        "org_slogan": "Trattamento acqua industriale e soluzioni OEM",
        "website_description": "Produttore globale di filtri acqua e sistemi a osmosi inversa per acquirenti OEM/ODM all'ingrosso",
        "worldwide": "In tutto il mondo",
        "award_1": "Oltre 27 anni di esperienza nella produzione per la filtrazione dell'acqua",
        "award_2": "Oltre 50 mercati di esportazione",
        "award_3": "Oltre 200 SKU di prodotti per la filtrazione dell'acqua",
        "cred_1": "Alcuni prodotti possono essere forniti o testati secondo i requisiti NSF/ANSI 42, 53 e 58",
        "cred_2": "Documenti di gestione qualità ISO 9001 disponibili su richiesta",
        "cred_3": "Documenti CE disponibili su richiesta ove applicabile",
        "cred_4": "Rapporti di prova SGS disponibili su richiesta ove applicabile",
        "cred_5": "Documenti relativi Halal disponibili su richiesta ove applicabile",
        "cred_cat_1": "supporto test prodotto",
        "cred_cat_2": "documento qualità",
        "cred_cat_3": "documento di mercato",
        "cred_cat_4": "documento di prova di terza parte",
        "offer_pp": "filtro PP melt blown",
        "offer_cto": "filtro CTO a blocco di carbone",
        "offer_gac": "filtro GAC",
        "offer_t33": "filtro in linea T33",
        "offer_uf": "membrana UF",
        "offer_ro": "membrana RO",
        "offer_purifier": "purificatore d'acqua",
        "offer_dispenser": "dispenser d'acqua",
        "offer_housing": "alloggiamento filtro",
        "offer_oem": "servizio di produzione OEM",
        "offer_odm": "servizio di progettazione ODM",
        "faq_cert_short": "Alcuni prodotti possono essere forniti o testati secondo i requisiti NSF/ANSI. Documenti ISO 9001, CE, SGS e relativi Halal sono disponibili su richiesta.",
        "faq_cert_tail": "Documenti ISO 9001, CE, SGS e relativi Halal sono disponibili su richiesta.",
        "cat_q1": "Questa categoria può essere fornita con imballaggio private label?",
        "cat_a1": "Sì. Yuchen Water supporta etichette prodotto, buste sigillate, scatole colorate, manuali, cartoni master e marcature pallet per ordini OEM/ODM.",
        "cat_q2": "Quali informazioni servono per un preventivo?",
        "cat_a2": "Inviare tipo di prodotto, dimensione richiesta, specifica, quantità stimata, porto di destinazione ed eventuali requisiti di branding o conformità.",
        "cat_q3": "Sono disponibili documenti di certificazione?",
        "crumb_home": '"name":"Home"',
        "crumb_products": '"name":"Prodotti"',
        "duplicate_footer": "ISO 9001, CE, SGS, documenti ISO 9001, CE, SGS, NSF/ANSI selezionati e relativi Halal disponibili su richiesta",
        "clean_footer": "ISO 9001, CE, SGS, NSF/ANSI selezionati e documenti relativi Halal disponibili su richiesta",
    },
    "nl": {
        "halal_about": "Halal-gerelateerde documenten zijn op aanvraag beschikbaar voor gekwalificeerde orders.",
        "quality_docs_short": "Kwaliteitsdocumenten beschikbaar op aanvraag · OEM/ODM",
        "quality_docs_plain": "Kwaliteitsdocumenten beschikbaar op aanvraag",
        "quality_docs_footer": "Yuchen Water · kwaliteitsdocumenten beschikbaar op aanvraag · OEM/ODM ·",
        "quality_management": "Kwaliteitsmanagementdocumenten beschikbaar op aanvraag.",
        "rights": "Alle rechten voorbehouden.",
        "cert_footer": "ISO 9001-, CE-, SGS-, geselecteerde NSF/ANSI- en Halal-gerelateerde documenten beschikbaar op aanvraag",
        "privacy": "Privacybeleid",
        "success_1": "Bedankt. Uw aanvraag is succesvol verzonden naar Yuchen Water via expresswater025@gmail.com.",
        "success_2": "Onze sales engineer neemt zo snel mogelijk contact met u op.",
        "success_3": "U kunt ons ook altijd bereiken via WhatsApp +86-19908311885 of e-mail expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Kwaliteitsdocumenten"',
        "schema_quality_value": "Geselecteerde producten kunnen worden geleverd of getest volgens NSF/ANSI 42, 53 en 58. ISO 9001-, CE-, SGS- en Halal-gerelateerde documenten zijn beschikbaar op aanvraag per model en marktvereiste.",
        "org_description": "Yuchen Water is een Chinese fabrikant van waterfiltratieproducten en levert PP, CTO, GAC, T33, UF, RO-membranen, waterzuiveraars, waterdispensers en filterbehuizingen aan wereldwijde B2B OEM/ODM-kopers.",
        "org_slogan": "Industriele waterbehandeling en OEM-oplossingen",
        "website_description": "Wereldwijde fabrikant van waterfilters en omgekeerde-osmosesystemen voor OEM/ODM groothandelskopers",
        "worldwide": "Wereldwijd",
        "award_1": "Meer dan 27 jaar ervaring in waterfiltratieproductie",
        "award_2": "Meer dan 50 exportmarkten",
        "award_3": "Meer dan 200 SKU's voor waterfiltratieproducten",
        "cred_1": "Geselecteerde producten kunnen worden geleverd of getest volgens NSF/ANSI 42, 53 en 58",
        "cred_2": "ISO 9001 kwaliteitsmanagementdocumenten beschikbaar op aanvraag",
        "cred_3": "CE-documenten beschikbaar op aanvraag waar van toepassing",
        "cred_4": "SGS-testrapporten beschikbaar op aanvraag waar van toepassing",
        "cred_5": "Halal-gerelateerde documenten beschikbaar op aanvraag waar van toepassing",
        "cred_cat_1": "producttestondersteuning",
        "cred_cat_2": "kwaliteitsdocument",
        "cred_cat_3": "marktdocument",
        "cred_cat_4": "testdocument van derden",
        "offer_pp": "PP melt blown filter",
        "offer_cto": "CTO koolstofblokfilter",
        "offer_gac": "GAC-filter",
        "offer_t33": "T33 inline filter",
        "offer_uf": "UF-membraan",
        "offer_ro": "RO-membraan",
        "offer_purifier": "waterzuiveraar",
        "offer_dispenser": "waterdispenser",
        "offer_housing": "filterbehuizing",
        "offer_oem": "OEM-productieservice",
        "offer_odm": "ODM-ontwerpservice",
        "faq_cert_short": "Geselecteerde producten kunnen worden geleverd of getest volgens NSF/ANSI-eisen. ISO 9001-, CE-, SGS- en Halal-gerelateerde documenten zijn beschikbaar op aanvraag.",
        "faq_cert_tail": "ISO 9001-, CE-, SGS- en Halal-gerelateerde documenten zijn beschikbaar op aanvraag.",
        "cat_q1": "Kan deze categorie met private-label verpakking worden geleverd?",
        "cat_a1": "Ja. Yuchen Water ondersteunt productlabels, verzegelde zakken, kleurdozen, handleidingen, master cartons en palletmarkeringen voor OEM/ODM-orders.",
        "cat_q2": "Welke informatie is nodig voor een offerte?",
        "cat_a2": "Stuur producttype, gewenste maat, specificatie, geschatte hoeveelheid, bestemmingshaven en eventuele merk- of compliance-eisen.",
        "cat_q3": "Zijn certificeringsdocumenten beschikbaar?",
        "crumb_home": '"name":"Home"',
        "crumb_products": '"name":"Producten"',
        "duplicate_footer": "ISO 9001, CE, SGS, ISO 9001-, CE-, SGS-, geselecteerde NSF/ANSI- en Halal-gerelateerde documenten beschikbaar op aanvraag",
        "clean_footer": "ISO 9001, CE, SGS, geselecteerde NSF/ANSI- en Halal-gerelateerde documenten beschikbaar op aanvraag",
        "inline_filter_title": "Inlinefilter",
    },
    "tr": {
        "halal_about": "Uygun siparişler için Halal ile ilgili belgeler talep üzerine sağlanabilir.",
        "quality_docs_short": "Kalite belgeleri talep üzerine sağlanır · OEM/ODM",
        "quality_docs_plain": "Kalite belgeleri talep üzerine sağlanır",
        "quality_docs_footer": "Yuchen Water · kalite belgeleri talep üzerine sağlanır · OEM/ODM ·",
        "quality_management": "Kalite yönetimi belgeleri talep üzerine sağlanır.",
        "rights": "Tüm hakları saklıdır.",
        "cert_footer": "ISO 9001, CE, SGS, seçili NSF/ANSI ve Halal ile ilgili belgeler talep üzerine sağlanır",
        "privacy": "Gizlilik Politikası",
        "success_1": "Teşekkürler. Talebiniz başarıyla gönderildi ve Yuchen Water'a expresswater025@gmail.com üzerinden ulaştı.",
        "success_2": "Satış mühendisimiz en kısa sürede sizinle iletişime geçecektir.",
        "success_3": "Bize her zaman WhatsApp +86-19908311885 veya e-posta expresswater025@gmail.com üzerinden de ulaşabilirsiniz.",
        "schema_quality_name": '"name":"Kalite belgeleri"',
        "schema_quality_value": "Seçili ürünler NSF/ANSI 42, 53 ve 58 gerekliliklerine göre tedarik edilebilir veya test edilebilir. ISO 9001, CE, SGS ve Halal ile ilgili belgeler ürün modeline ve pazar gereksinimine göre talep üzerine sağlanır.",
        "org_description": "Yuchen Water, küresel B2B OEM/ODM alıcıları için PP, CTO, GAC, T33, UF, RO membran, su arıtma cihazı, su sebili ve filtre gövdesi tedarik eden Çinli bir su filtrasyon üreticisidir.",
        "org_slogan": "Endüstriyel su arıtma ve OEM çözümleri",
        "website_description": "OEM/ODM toptan alıcılar için küresel su filtresi ve ters ozmoz sistemi üreticisi",
        "worldwide": "Dünya çapında",
        "award_1": "27 yıldan fazla su filtrasyon üretim deneyimi",
        "award_2": "50'den fazla ihracat pazarı",
        "award_3": "200'den fazla su filtrasyon ürünü SKU'su",
        "cred_1": "Seçili ürünler NSF/ANSI 42, 53 ve 58 gerekliliklerine göre tedarik edilebilir veya test edilebilir",
        "cred_2": "ISO 9001 kalite yönetimi belgeleri talep üzerine sağlanır",
        "cred_3": "Uygun olduğunda CE belgeleri talep üzerine sağlanır",
        "cred_4": "Uygun olduğunda SGS test raporları talep üzerine sağlanır",
        "cred_5": "Uygun olduğunda Halal ile ilgili belgeler talep üzerine sağlanır",
        "cred_cat_1": "ürün test desteği",
        "cred_cat_2": "kalite belgesi",
        "cred_cat_3": "pazar belgesi",
        "cred_cat_4": "üçüncü taraf test belgesi",
        "offer_pp": "PP melt blown filtre",
        "offer_cto": "CTO karbon blok filtre",
        "offer_gac": "GAC filtre",
        "offer_t33": "T33 inline filtre",
        "offer_uf": "UF membran",
        "offer_ro": "RO membran",
        "offer_purifier": "su arıtma cihazı",
        "offer_dispenser": "su sebili",
        "offer_housing": "filtre gövdesi",
        "offer_oem": "OEM üretim hizmeti",
        "offer_odm": "ODM tasarım hizmeti",
        "faq_cert_short": "Seçili ürünler NSF/ANSI gerekliliklerine göre tedarik edilebilir veya test edilebilir. ISO 9001, CE, SGS ve Halal ile ilgili belgeler talep üzerine sağlanır.",
        "faq_cert_tail": "ISO 9001, CE, SGS ve Halal ile ilgili belgeler talep üzerine sağlanır.",
        "cat_q1": "Bu kategori özel markalı ambalajla tedarik edilebilir mi?",
        "cat_a1": "Evet. Yuchen Water, OEM/ODM siparişleri için ürün etiketleri, mühürlü poşetler, renkli kutular, kullanım talimatları, ana kartonlar ve palet işaretlerini destekler.",
        "cat_q2": "Teklif için hangi bilgiler gereklidir?",
        "cat_a2": "Lütfen ürün tipi, hedef ölçü, teknik özellik, tahmini adet, varış limanı ve marka veya uyumluluk gereksinimlerini gönderin.",
        "cat_q3": "Sertifika belgeleri mevcut mu?",
        "crumb_home": '"name":"Ana sayfa"',
        "crumb_products": '"name":"Ürünler"',
        "duplicate_footer": "ISO 9001, CE, SGS, ISO 9001, CE, SGS, seçili NSF/ANSI ve Halal ile ilgili belgeler talep üzerine sağlanır",
        "clean_footer": "ISO 9001, CE, SGS, seçili NSF/ANSI ve Halal ile ilgili belgeler talep üzerine sağlanır",
    },
    "pl": {
        "halal_about": "Dokumenty związane z Halal są dostępne na życzenie dla kwalifikujących się zamówień.",
        "quality_docs_short": "Dokumenty jakości dostępne na życzenie · OEM/ODM",
        "quality_docs_plain": "Dokumenty jakości dostępne na życzenie",
        "quality_docs_footer": "Yuchen Water · dokumenty jakości dostępne na życzenie · OEM/ODM ·",
        "quality_management": "Dokumenty zarządzania jakością dostępne na życzenie.",
        "rights": "Wszelkie prawa zastrzeżone.",
        "cert_footer": "dokumenty ISO 9001, CE, SGS, wybrane NSF/ANSI oraz związane z Halal dostępne na życzenie",
        "privacy": "Polityka prywatności",
        "success_1": "Dziękujemy. Zapytanie zostało pomyślnie wysłane do Yuchen Water na adres expresswater025@gmail.com.",
        "success_2": "Nasz inżynier sprzedaży skontaktuje się z Tobą tak szybko, jak to możliwe.",
        "success_3": "Możesz też skontaktować się z nami w dowolnym momencie przez WhatsApp +86-19908311885 lub e-mail expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Dokumenty jakości"',
        "schema_quality_value": "Wybrane produkty mogą być dostarczone lub testowane zgodnie z wymaganiami NSF/ANSI 42, 53 i 58. Dokumenty ISO 9001, CE, SGS oraz związane z Halal są dostępne na życzenie według modelu produktu i wymagań rynku.",
        "org_description": "Yuchen Water to chiński producent produktów do filtracji wody, dostarczający PP, CTO, GAC, T33, UF, membrany RO, oczyszczacze wody, dystrybutory wody i obudowy filtrów dla globalnych nabywców B2B OEM/ODM.",
        "org_slogan": "Przemysłowe uzdatnianie wody i rozwiązania OEM",
        "website_description": "Globalny producent filtrów do wody i systemów odwróconej osmozy dla hurtowych nabywców OEM/ODM",
        "worldwide": "Na całym świecie",
        "award_1": "Ponad 27 lat doświadczenia w produkcji filtracji wody",
        "award_2": "Ponad 50 rynków eksportowych",
        "award_3": "Ponad 200 SKU produktów do filtracji wody",
        "cred_1": "Wybrane produkty mogą być dostarczone lub testowane zgodnie z wymaganiami NSF/ANSI 42, 53 i 58",
        "cred_2": "Dokumenty zarządzania jakością ISO 9001 dostępne na życzenie",
        "cred_3": "Dokumenty CE dostępne na życzenie tam, gdzie dotyczy",
        "cred_4": "Raporty testowe SGS dostępne na życzenie tam, gdzie dotyczy",
        "cred_5": "Dokumenty związane z Halal dostępne na życzenie tam, gdzie dotyczy",
        "cred_cat_1": "wsparcie testów produktu",
        "cred_cat_2": "dokument jakości",
        "cred_cat_3": "dokument rynkowy",
        "cred_cat_4": "dokument testu strony trzeciej",
        "offer_pp": "filtr PP melt blown",
        "offer_cto": "filtr blokowy CTO z węglem",
        "offer_gac": "filtr GAC",
        "offer_t33": "filtr liniowy T33",
        "offer_uf": "membrana UF",
        "offer_ro": "membrana RO",
        "offer_purifier": "oczyszczacz wody",
        "offer_dispenser": "dystrybutor wody",
        "offer_housing": "obudowa filtra",
        "offer_oem": "usługa produkcji OEM",
        "offer_odm": "usługa projektowania ODM",
        "faq_cert_short": "Wybrane produkty mogą być dostarczone lub testowane zgodnie z wymaganiami NSF/ANSI. Dokumenty ISO 9001, CE, SGS oraz związane z Halal są dostępne na życzenie.",
        "faq_cert_tail": "Dokumenty ISO 9001, CE, SGS oraz związane z Halal są dostępne na życzenie.",
        "cat_q1": "Czy ta kategoria może być dostarczana z opakowaniem private label?",
        "cat_a1": "Tak. Yuchen Water obsługuje etykiety produktów, woreczki zgrzewane, pudełka kolorowe, instrukcje, kartony zbiorcze i oznaczenia palet dla zamówień OEM/ODM.",
        "cat_q2": "Jakie informacje są potrzebne do wyceny?",
        "cat_a2": "Prosimy przesłać typ produktu, wymagany rozmiar, specyfikację, szacowaną ilość, port docelowy oraz wymagania dotyczące marki lub zgodności.",
        "cat_q3": "Czy dokumenty certyfikacyjne są dostępne?",
        "crumb_home": '"name":"Strona główna"',
        "crumb_products": '"name":"Produkty"',
        "duplicate_footer": "ISO 9001, CE, SGS, dokumenty ISO 9001, CE, SGS, wybrane NSF/ANSI oraz związane z Halal dostępne na życzenie",
        "clean_footer": "ISO 9001, CE, SGS, wybrane NSF/ANSI oraz dokumenty związane z Halal dostępne na życzenie",
    },
    "cs": {
        "halal_about": "Dokumenty související s Halal jsou pro kvalifikované objednávky dostupné na vyžádání.",
        "quality_docs_short": "Dokumenty kvality dostupné na vyžádání · OEM/ODM",
        "quality_docs_plain": "Dokumenty kvality dostupné na vyžádání",
        "quality_docs_footer": "Yuchen Water · dokumenty kvality dostupné na vyžádání · OEM/ODM ·",
        "quality_management": "Dokumenty řízení kvality dostupné na vyžádání.",
        "rights": "Všechna práva vyhrazena.",
        "cert_footer": "dokumenty ISO 9001, CE, SGS, vybrané NSF/ANSI a související s Halal jsou dostupné na vyžádání",
        "privacy": "Zásady ochrany osobních údajů",
        "success_1": "Děkujeme. Vaše poptávka byla úspěšně odeslána společnosti Yuchen Water na expresswater025@gmail.com.",
        "success_2": "Náš obchodní inženýr vás bude co nejdříve kontaktovat.",
        "success_3": "Můžete nás také kdykoli kontaktovat přes WhatsApp +86-19908311885 nebo e-mail expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Dokumenty kvality"',
        "schema_quality_value": "Vybrané produkty mohou být dodány nebo testovány podle požadavků NSF/ANSI 42, 53 a 58. Dokumenty ISO 9001, CE, SGS a související s Halal jsou dostupné na vyžádání podle modelu produktu a požadavků trhu.",
        "org_description": "Yuchen Water je čínský výrobce produktů pro filtraci vody, který dodává PP, CTO, GAC, T33, UF, RO membrány, čističky vody, dávkovače vody a filtrační pouzdra globálním B2B OEM/ODM zákazníkům.",
        "org_slogan": "Průmyslová úprava vody a OEM řešení",
        "website_description": "Globální výrobce vodních filtrů a systémů reverzní osmózy pro velkoobchodní OEM/ODM zákazníky",
        "worldwide": "Celosvětově",
        "award_1": "Více než 27 let zkušeností s výrobou vodní filtrace",
        "award_2": "Více než 50 exportních trhů",
        "award_3": "Více než 200 SKU produktů pro filtraci vody",
        "cred_1": "Vybrané produkty mohou být dodány nebo testovány podle požadavků NSF/ANSI 42, 53 a 58",
        "cred_2": "Dokumenty řízení kvality ISO 9001 dostupné na vyžádání",
        "cred_3": "Dokumenty CE dostupné na vyžádání, kde je to relevantní",
        "cred_4": "Zkušební zprávy SGS dostupné na vyžádání, kde je to relevantní",
        "cred_5": "Dokumenty související s Halal dostupné na vyžádání, kde je to relevantní",
        "cred_cat_1": "podpora testování produktů",
        "cred_cat_2": "dokument kvality",
        "cred_cat_3": "tržní dokument",
        "cred_cat_4": "dokument testu třetí strany",
        "offer_pp": "PP melt blown filtr",
        "offer_cto": "CTO uhlíkový blokový filtr",
        "offer_gac": "GAC filtr",
        "offer_t33": "T33 inline filtr",
        "offer_uf": "UF membrána",
        "offer_ro": "RO membrána",
        "offer_purifier": "čistička vody",
        "offer_dispenser": "dávkovač vody",
        "offer_housing": "filtrační pouzdro",
        "offer_oem": "služba OEM výroby",
        "offer_odm": "služba ODM návrhu",
        "faq_cert_short": "Vybrané produkty mohou být dodány nebo testovány podle požadavků NSF/ANSI. Dokumenty ISO 9001, CE, SGS a související s Halal jsou dostupné na vyžádání.",
        "faq_cert_tail": "Dokumenty ISO 9001, CE, SGS a související s Halal jsou dostupné na vyžádání.",
        "cat_q1": "Lze tuto kategorii dodat s privátním balením?",
        "cat_a1": "Ano. Yuchen Water podporuje produktové etikety, uzavřené sáčky, barevné krabice, návody, hlavní kartony a značení palet pro objednávky OEM/ODM.",
        "cat_q2": "Jaké informace jsou potřeba pro cenovou nabídku?",
        "cat_a2": "Zašlete prosím typ produktu, požadovaný rozměr, specifikaci, odhadované množství, cílový přístav a požadavky na značku nebo shodu.",
        "cat_q3": "Jsou dostupné certifikační dokumenty?",
        "crumb_home": '"name":"Domů"',
        "crumb_products": '"name":"Produkty"',
        "duplicate_footer": "ISO 9001, CE, SGS, dokumenty ISO 9001, CE, SGS, vybrané NSF/ANSI a související s Halal jsou dostupné na vyžádání",
        "clean_footer": "ISO 9001, CE, SGS, vybrané NSF/ANSI a dokumenty související s Halal jsou dostupné na vyžádání",
    },
    "sk": {
        "halal_about": "Dokumenty súvisiace s Halal sú pre kvalifikované objednávky dostupné na vyžiadanie.",
        "quality_docs_short": "Dokumenty kvality dostupné na vyžiadanie · OEM/ODM",
        "quality_docs_plain": "Dokumenty kvality dostupné na vyžiadanie",
        "quality_docs_footer": "Yuchen Water · dokumenty kvality dostupné na vyžiadanie · OEM/ODM ·",
        "quality_management": "Dokumenty riadenia kvality dostupné na vyžiadanie.",
        "rights": "Všetky práva vyhradené.",
        "cert_footer": "dokumenty ISO 9001, CE, SGS, vybrané NSF/ANSI a súvisiace s Halal sú dostupné na vyžiadanie",
        "privacy": "Zásady ochrany osobných údajov",
        "success_1": "Ďakujeme. Vaša požiadavka bola úspešne odoslaná spoločnosti Yuchen Water na expresswater025@gmail.com.",
        "success_2": "Náš obchodný inžinier vás bude čo najskôr kontaktovať.",
        "success_3": "Môžete nás tiež kedykoľvek kontaktovať cez WhatsApp +86-19908311885 alebo e-mail expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Dokumenty kvality"',
        "schema_quality_value": "Vybrané produkty môžu byť dodané alebo testované podľa požiadaviek NSF/ANSI 42, 53 a 58. Dokumenty ISO 9001, CE, SGS a súvisiace s Halal sú dostupné na vyžiadanie podľa modelu produktu a požiadaviek trhu.",
        "org_description": "Yuchen Water je čínsky výrobca produktov na filtráciu vody, ktorý dodáva PP, CTO, GAC, T33, UF, RO membrány, čističky vody, dávkovače vody a filtračné puzdrá globálnym B2B OEM/ODM zákazníkom.",
        "org_slogan": "Priemyselná úprava vody a OEM riešenia",
        "website_description": "Globálny výrobca vodných filtrov a systémov reverznej osmózy pre veľkoobchodných OEM/ODM zákazníkov",
        "worldwide": "Celosvetovo",
        "award_1": "Viac ako 27 rokov skúseností s výrobou vodnej filtrácie",
        "award_2": "Viac ako 50 exportných trhov",
        "award_3": "Viac ako 200 SKU produktov na filtráciu vody",
        "cred_1": "Vybrané produkty môžu byť dodané alebo testované podľa požiadaviek NSF/ANSI 42, 53 a 58",
        "cred_2": "Dokumenty riadenia kvality ISO 9001 dostupné na vyžiadanie",
        "cred_3": "Dokumenty CE dostupné na vyžiadanie, kde je to relevantné",
        "cred_4": "Skúšobné správy SGS dostupné na vyžiadanie, kde je to relevantné",
        "cred_5": "Dokumenty súvisiace s Halal dostupné na vyžiadanie, kde je to relevantné",
        "cred_cat_1": "podpora testovania produktov",
        "cred_cat_2": "dokument kvality",
        "cred_cat_3": "trhový dokument",
        "cred_cat_4": "dokument testu tretej strany",
        "offer_pp": "PP melt blown filter",
        "offer_cto": "CTO uhlíkový blokový filter",
        "offer_gac": "GAC filter",
        "offer_t33": "T33 inline filter",
        "offer_uf": "UF membrána",
        "offer_ro": "RO membrána",
        "offer_purifier": "čistička vody",
        "offer_dispenser": "dávkovač vody",
        "offer_housing": "filtračné puzdro",
        "offer_oem": "služba OEM výroby",
        "offer_odm": "služba ODM návrhu",
        "faq_cert_short": "Vybrané produkty môžu byť dodané alebo testované podľa požiadaviek NSF/ANSI. Dokumenty ISO 9001, CE, SGS a súvisiace s Halal sú dostupné na vyžiadanie.",
        "faq_cert_tail": "Dokumenty ISO 9001, CE, SGS a súvisiace s Halal sú dostupné na vyžiadanie.",
        "cat_q1": "Je možné túto kategóriu dodať s privátnym balením?",
        "cat_a1": "Áno. Yuchen Water podporuje produktové etikety, uzavreté vrecká, farebné krabice, návody, hlavné kartóny a značenie paliet pre objednávky OEM/ODM.",
        "cat_q2": "Aké informácie sú potrebné pre cenovú ponuku?",
        "cat_a2": "Pošlite prosím typ produktu, požadovaný rozmer, špecifikáciu, odhadované množstvo, cieľový prístav a požiadavky na značku alebo zhodu.",
        "cat_q3": "Sú dostupné certifikačné dokumenty?",
        "crumb_home": '"name":"Domov"',
        "crumb_products": '"name":"Produkty"',
        "duplicate_footer": "ISO 9001, CE, SGS, dokumenty ISO 9001, CE, SGS, vybrané NSF/ANSI a súvisiace s Halal sú dostupné na vyžiadanie",
        "clean_footer": "ISO 9001, CE, SGS, vybrané NSF/ANSI a dokumenty súvisiace s Halal sú dostupné na vyžiadanie",
        "inline_filter_title": "Líniový filter",
    },
    "hu": {
        "halal_about": "A Halal kapcsolódó dokumentumok minősített rendelésekhez kérésre elérhetők.",
        "quality_docs_short": "Minőségi dokumentumok kérésre elérhetők · OEM/ODM",
        "quality_docs_plain": "Minőségi dokumentumok kérésre elérhetők",
        "quality_docs_footer": "Yuchen Water · minőségi dokumentumok kérésre elérhetők · OEM/ODM ·",
        "quality_management": "Minőségirányítási dokumentumok kérésre elérhetők.",
        "rights": "Minden jog fenntartva.",
        "cert_footer": "ISO 9001, CE, SGS, kiválasztott NSF/ANSI és Halal kapcsolódó dokumentumok kérésre elérhetők",
        "privacy": "Adatvédelmi irányelvek",
        "success_1": "Köszönjük. Megkeresése sikeresen elküldésre került a Yuchen Water részére az expresswater025@gmail.com címre.",
        "success_2": "Értékesítési mérnökünk a lehető leghamarabb felveszi Önnel a kapcsolatot.",
        "success_3": "Bármikor kapcsolatba léphet velünk WhatsAppon: +86-19908311885 vagy e-mailben: expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Minőségi dokumentumok"',
        "schema_quality_value": "A kiválasztott termékek NSF/ANSI 42, 53 és 58 követelmények szerint szállíthatók vagy tesztelhetők. ISO 9001, CE, SGS és Halal kapcsolódó dokumentumok termékmodell és piaci követelmény szerint kérésre elérhetők.",
        "org_description": "A Yuchen Water kínai vízszűrési termékgyártó, amely PP, CTO, GAC, T33, UF, RO membrán, víztisztító, vízadagoló és szűrőház termékeket szállít globális B2B OEM/ODM vevőknek.",
        "org_slogan": "Ipari vízkezelés és OEM megoldások",
        "website_description": "Globális vízszűrő és fordított ozmózis rendszer gyártó OEM/ODM nagykereskedelmi vevők számára",
        "worldwide": "Világszerte",
        "award_1": "Több mint 27 év vízszűrési gyártási tapasztalat",
        "award_2": "Több mint 50 exportpiac",
        "award_3": "Több mint 200 vízszűrési termék SKU",
        "cred_1": "A kiválasztott termékek NSF/ANSI 42, 53 és 58 követelmények szerint szállíthatók vagy tesztelhetők",
        "cred_2": "ISO 9001 minőségirányítási dokumentumok kérésre elérhetők",
        "cred_3": "CE dokumentumok kérésre elérhetők, ahol alkalmazható",
        "cred_4": "SGS vizsgálati jelentések kérésre elérhetők, ahol alkalmazható",
        "cred_5": "Halal kapcsolódó dokumentumok kérésre elérhetők, ahol alkalmazható",
        "cred_cat_1": "termékteszt támogatás",
        "cred_cat_2": "minőségi dokumentum",
        "cred_cat_3": "piaci dokumentum",
        "cred_cat_4": "harmadik fél vizsgálati dokumentuma",
        "offer_pp": "PP melt blown szűrő",
        "offer_cto": "CTO szénblokk szűrő",
        "offer_gac": "GAC szűrő",
        "offer_t33": "T33 inline szűrő",
        "offer_uf": "UF membrán",
        "offer_ro": "RO membrán",
        "offer_purifier": "víztisztító",
        "offer_dispenser": "vízadagoló",
        "offer_housing": "szűrőház",
        "offer_oem": "OEM gyártási szolgáltatás",
        "offer_odm": "ODM tervezési szolgáltatás",
        "faq_cert_short": "A kiválasztott termékek NSF/ANSI követelmények szerint szállíthatók vagy tesztelhetők. ISO 9001, CE, SGS és Halal kapcsolódó dokumentumok kérésre elérhetők.",
        "faq_cert_tail": "ISO 9001, CE, SGS és Halal kapcsolódó dokumentumok kérésre elérhetők.",
        "cat_q1": "Szállítható ez a kategória saját márkás csomagolással?",
        "cat_a1": "Igen. A Yuchen Water támogatja a termékcímkéket, lezárt tasakokat, színes dobozokat, használati útmutatókat, gyűjtőkartonokat és raklapjelöléseket OEM/ODM rendelésekhez.",
        "cat_q2": "Milyen információ szükséges az árajánlathoz?",
        "cat_a2": "Kérjük, küldje el a terméktípust, kívánt méretet, specifikációt, becsült mennyiséget, rendeltetési kikötőt és minden márka- vagy megfelelőségi igényt.",
        "cat_q3": "Elérhetők tanúsítási dokumentumok?",
        "crumb_home": '"name":"Kezdőlap"',
        "crumb_products": '"name":"Termékek"',
        "duplicate_footer": "ISO 9001, CE, SGS, ISO 9001, CE, SGS, kiválasztott NSF/ANSI és Halal kapcsolódó dokumentumok kérésre elérhetők",
        "clean_footer": "ISO 9001, CE, SGS, kiválasztott NSF/ANSI és Halal kapcsolódó dokumentumok kérésre elérhetők",
    },
    "ro": {
        "halal_about": "Documentele legate de Halal sunt disponibile la cerere pentru comenzile eligibile.",
        "quality_docs_short": "Documente de calitate disponibile la cerere · OEM/ODM",
        "quality_docs_plain": "Documente de calitate disponibile la cerere",
        "quality_docs_footer": "Yuchen Water · documente de calitate disponibile la cerere · OEM/ODM ·",
        "quality_management": "Documente de management al calității disponibile la cerere.",
        "rights": "Toate drepturile rezervate.",
        "cert_footer": "documente ISO 9001, CE, SGS, NSF/ANSI selectate și legate de Halal disponibile la cerere",
        "privacy": "Politica de confidențialitate",
        "success_1": "Vă mulțumim. Solicitarea dvs. a fost trimisă cu succes către Yuchen Water la expresswater025@gmail.com.",
        "success_2": "Inginerul nostru de vânzări vă va contacta cât mai curând posibil.",
        "success_3": "Ne puteți contacta oricând și pe WhatsApp +86-19908311885 sau prin e-mail la expresswater025@gmail.com.",
        "schema_quality_name": '"name":"Documente de calitate"',
        "schema_quality_value": "Produsele selectate pot fi furnizate sau testate conform cerințelor NSF/ANSI 42, 53 și 58. Documentele ISO 9001, CE, SGS și cele legate de Halal sunt disponibile la cerere în funcție de modelul produsului și cerințele pieței.",
        "org_description": "Yuchen Water este un producător chinez de produse pentru filtrarea apei, furnizând PP, CTO, GAC, T33, UF, membrane RO, purificatoare de apă, dozatoare de apă și carcase de filtre pentru cumpărători B2B OEM/ODM globali.",
        "org_slogan": "Tratarea apei industriale și soluții OEM",
        "website_description": "Producător global de filtre de apă și sisteme de osmoză inversă pentru cumpărători angro OEM/ODM",
        "worldwide": "La nivel mondial",
        "award_1": "Peste 27 de ani de experiență în producția de filtrare a apei",
        "award_2": "Peste 50 de piețe de export",
        "award_3": "Peste 200 de SKU-uri de produse pentru filtrarea apei",
        "cred_1": "Produsele selectate pot fi furnizate sau testate conform cerințelor NSF/ANSI 42, 53 și 58",
        "cred_2": "Documente de management al calității ISO 9001 disponibile la cerere",
        "cred_3": "Documente CE disponibile la cerere acolo unde se aplică",
        "cred_4": "Rapoarte de testare SGS disponibile la cerere acolo unde se aplică",
        "cred_5": "Documente legate de Halal disponibile la cerere acolo unde se aplică",
        "cred_cat_1": "suport pentru testarea produselor",
        "cred_cat_2": "document de calitate",
        "cred_cat_3": "document de piață",
        "cred_cat_4": "document de testare terță parte",
        "offer_pp": "filtru PP melt blown",
        "offer_cto": "filtru CTO bloc de carbon",
        "offer_gac": "filtru GAC",
        "offer_t33": "filtru inline T33",
        "offer_uf": "membrană UF",
        "offer_ro": "membrană RO",
        "offer_purifier": "purificator de apă",
        "offer_dispenser": "dozator de apă",
        "offer_housing": "carcasă filtru",
        "offer_oem": "serviciu de producție OEM",
        "offer_odm": "serviciu de proiectare ODM",
        "faq_cert_short": "Produsele selectate pot fi furnizate sau testate conform cerințelor NSF/ANSI. Documentele ISO 9001, CE, SGS și cele legate de Halal sunt disponibile la cerere.",
        "faq_cert_tail": "Documentele ISO 9001, CE, SGS și cele legate de Halal sunt disponibile la cerere.",
        "cat_q1": "Această categorie poate fi livrată cu ambalaj private label?",
        "cat_a1": "Da. Yuchen Water oferă etichete de produs, pungi sigilate, cutii color, instrucțiuni, cartoane master și marcaje pe paleți pentru comenzi OEM/ODM.",
        "cat_q2": "Ce informații sunt necesare pentru ofertă?",
        "cat_a2": "Vă rugăm să trimiteți tipul produsului, dimensiunea dorită, specificația, cantitatea estimată, portul de destinație și orice cerințe de branding sau conformitate.",
        "cat_q3": "Sunt disponibile documente de certificare?",
        "crumb_home": '"name":"Acasă"',
        "crumb_products": '"name":"Produse"',
        "duplicate_footer": "ISO 9001, CE, SGS, documente ISO 9001, CE, SGS, NSF/ANSI selectate și legate de Halal disponibile la cerere",
        "clean_footer": "ISO 9001, CE, SGS, documente NSF/ANSI selectate și legate de Halal disponibile la cerere",
    },
}


def build_replacements(lang: str) -> dict[str, str]:
    trans = TRANSLATIONS[lang]
    replacements = {}
    for key, source in COMMON_SOURCES.items():
        if key in trans:
            replacements[source] = trans[key]
    replacements[
        "ISO 9001, CE, SGS and Halal-related documents are available upon request by product model and market requirement."
    ] = trans["schema_quality_value"].split(". ", 1)[-1]
    if "duplicate_footer" in trans:
        replacements[trans["duplicate_footer"]] = trans["clean_footer"]
    if "inline_filter_title" in trans:
        replacements["Inline filter"] = trans["inline_filter_title"]
        replacements["inline filter"] = trans["inline_filter_title"].lower()
    return replacements


def normalize_title(html: str) -> str:
    def replace_title(match: re.Match[str]) -> str:
        title = match.group(1)
        parts = [part.strip() for part in title.split("|")]
        if len(parts) >= 3 and parts[-1] == "Yuchen Water":
            middle = " ".join(parts[1:-1])
            if re.search(
                r"\b(product|inline filter|t33 inline filter|water purifier|filter cartridge|ro membrane|water dispenser|filter housing|carbon block|alkaline purifier|post t33|antibacterial mineralization)\b",
                middle,
                re.I,
            ):
                return f"<title>{parts[0]} | Yuchen Water</title>"
        return match.group(0)

    return re.sub(r"<title>(.*?)</title>", replace_title, html, flags=re.I | re.S)


def main() -> None:
    changed = 0
    for lang in TRANSLATIONS:
        replacements = build_replacements(lang)
        for path in (ROOT / lang).glob("*.html"):
            original = path.read_text(encoding="utf-8")
            updated = original
            for source, target in replacements.items():
                updated = updated.replace(source, target)
            updated = normalize_title(updated)
            if updated != original:
                path.write_text(updated, encoding="utf-8")
                changed += 1
                print(path.relative_to(ROOT))
    print(f"changed_files={changed}")


if __name__ == "__main__":
    main()
